---
title: "Plasmid curation"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

```{r}
library(tidyverse) 
source("./scripts/mobsuite/mobsuite_functions.R")
```


```{r}
df <- readRDS("./data/dataset/df.RDS") 
```

```{r}
# Mobtyper Results
mobtyper <- read_mobtyper_results(path='./data/mobsuite/CRKP_mobtyper_results.txt',df)
mobsuite_contigs <- read_mobtyper_results(path='./data/mobsuite/CRKP_contig_report.txt',df)
mobsuite_contigs$location <- ifelse(mobsuite_contigs$primary_cluster_id=="-","chromosome",mobsuite_contigs$primary_cluster_id)

# save reports
saveRDS(mobtyper,file="./data/mobsuite/mobtyper.RDS")
saveRDS(mobsuite_contigs,file="./data/mobsuite/mobsuite_contigs.RDS") 

# Convert Mobsuite Data into Binary Matrix
mash_nn_matrix <- get_mobtyper_mash_nn_matrix(df,mobtyper)  
cluster_matrix <- get_mobtyper_cluster_matrix(df,mobtyper) 

# Save matrices
saveRDS(mash_nn_matrix,file="./data/mobsuite/plasmid_mash_nn_matrix.RDS")
saveRDS(cluster_matrix,file="./data/mobsuite/plasmid_cluster_matrix.RDS") 
```