---
title: "multifitMk rate differences table"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
knitr::opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/') 
```

# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
# Packages
packages <- c("tidyverse","lmtest")   
# Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T)) 
# Load function
source('./lib/consistent_themes.R')
# Print
Sys.info()
sessionInfo() 
```

# Load
```{r}
single_ER <- readRDS("./data/fitmultiMk_rate_differences/fitmultiMk_uniform_regimes_ER.RDS")
single_ARD <-  readRDS("./data/fitmultiMk_rate_differences/fitmultiMk_uniform_regimes_ARD.RDS")
multi_ER <-  readRDS("./data/fitmultiMk_rate_differences/fitmultiMk_clade_regimes_ER.RDS")
multi_ARD <-  readRDS("./data/fitmultiMk_rate_differences/fitmultiMk_clade_regimes_ARD.RDS")
```

# Extract data
```{r}
pheno <- c("blbli","MVB","IR") %>% paste0(.,"_dich_num")

extract_data <- function(fitmultiMK_obj){
  num_rates <- length(fitmultiMK_obj$rates)
  R1 = fitmultiMK_obj$rates[[1]]
  R2 = ifelse(num_rates==1,NA,fitmultiMK_obj$rates[[2]])
  log_likelihood <- fitmultiMK_obj$logLik
  AIC=AIC(fitmultiMK_obj)
  data.frame(R1,R2,log_likelihood,AIC)
}

single_ER_data <- lapply(single_ER,extract_data) %>% do.call(rbind,.) %>% mutate(model="ER",phenotype=pheno)
single_ARD_data <- lapply(single_ARD,extract_data) %>% do.call(rbind,.) %>% mutate(model="ARD",phenotype=pheno)

extract_data_two_clade <- function(fitmultiMK_obj){
  num_rates <- length(fitmultiMK_obj$rates)
  CII_R1 <- fitmultiMK_obj$rates[[1]]
  CI_R1 <- ifelse(num_rates==2,fitmultiMK_obj$rates[[2]],fitmultiMK_obj$rates[[3]])
  if(num_rates>2){
    CI_R2 <- fitmultiMK_obj$rates[[4]]
    CII_R2 <- fitmultiMK_obj$rates[[2]]
  } else {
    CI_R2 =NA
    CII_R2 =NA
  }
  multi_regime_log_likelihood <- fitmultiMK_obj$logLik
  multi_regime_AIC=AIC(fitmultiMK_obj)
  data.frame(CI_R1,CI_R2,CII_R1,CII_R2,multi_regime_log_likelihood,multi_regime_AIC)
}

multi_ER_data <- lapply(multi_ER,extract_data_two_clade) %>% do.call(rbind,.) %>% mutate(model="ER",phenotype=pheno)
multi_ARD_data <- lapply(multi_ARD,extract_data_two_clade) %>% do.call(rbind,.) %>% mutate(model="ARD",phenotype=pheno)
```

# Joint ER and ARD datapoints
## Merge
```{r}
joint_ER_df <- left_join(single_ER_data,multi_ER_data) 
joint_ARD_df <-  left_join(single_ARD_data,multi_ARD_data) 

total_df <- rbind(joint_ER_df,joint_ARD_df)
```

# Likelihood ratio test
```{r}
# ER
lrt_res_ER <- matrix(ncol=4,nrow=3) %>% `colnames<-`(c("phenotype","model","LRT_chisq","LRT_pvalue")) %>% as.data.frame
for(i in seq_len(length(single_ER))){
  results <- lrtest(single_ER[[i]],multi_ER[[i]])
  lrt_res_ER[i,"phenotype"] <- names(single_ER)[[i]]
  lrt_res_ER[i,"model"] <- 'ER'
  lrt_res_ER[i,"LRT_chisq"] <- results[['Chisq']] %>% subset(is.na(.)==F) %>% as.numeric
  lrt_res_ER[i,"LRT_pvalue"] <-results[['Pr(>Chisq)']] %>% subset(is.na(.)==F) %>% as.numeric
}

# ARD
lrt_res_ARD <- matrix(ncol=4,nrow=3) %>% `colnames<-`(c("phenotype","model","LRT_chisq","LRT_pvalue"))%>% as.data.frame
for(i in seq_len(length(single_ARD))){
  results <- lrtest(single_ARD[[i]],multi_ARD[[i]])
  lrt_res_ARD[i,"phenotype"] <- names(single_ARD)[[i]]
  lrt_res_ARD[i,"model"] <- 'ARD'
  lrt_res_ARD[i,"LRT_chisq"] <- results[['Chisq']] %>% subset(is.na(.)==F) %>% as.numeric
  lrt_res_ARD[i,"LRT_pvalue"] <-results[['Pr(>Chisq)']] %>% subset(is.na(.)==F) %>% as.numeric
} 

total_lrt_res <- rbind(lrt_res_ER,lrt_res_ARD)
```

# Create and save final table
```{r}
final_df <- left_join(total_df,total_lrt_res)  
paste0("Final data table")
favorite_kable(final_df)
# save
saveRDS(final_df,'./data/fitmultiMk_rate_differences/fitmultiMk_rate_differences_table.RDS')
```
