---
title: "curate_KPC_plasmid_matrix"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE) 
rm(list = ls())
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
``` 

```{r}
library(ape)
library(tidyverse)
``` 

```{r} 
tr <- read.tree(file=paste0('./data/tree/tree.treefile'))
```

```{r}
KPC_containing_cluster_mat <- readRDS("./data/KPC_plasmid/KPC_containing_clusters_mat.RDS")    %>% {ifelse(.=="KPC Plasmid",1,0)} %>% .[match(tr$tip.label,rownames(.)),] %>% as.data.frame %>% select_if(.,colSums(.) > 1 & colSums(.) < nrow(.) - 2) %>% as.matrix
KPC_containing_plasmids_mat <- readRDS("./data/KPC_plasmid/KPC_containing_plasmids_mat.RDS")  %>% {ifelse(.=="KPC Plasmid",1,0)} %>% .[match(tr$tip.label,rownames(.)),] %>% as.data.frame %>% select_if(.,colSums(.) > 1 & colSums(.) < nrow(.) - 2) %>% as.matrix
```

```{r}
saveRDS(KPC_containing_cluster_mat,"./data/GWAS/matrices/KPC_containing_cluster_mat.RDS")
saveRDS(KPC_containing_plasmids_mat,"../data/GWAS/matrices/KPC_containing_plasmids_mat.RDS")
```
