---
title: "Multivariable regression using modified purposeful selection algorithm using phylogenetically-aware outcomes"
author: "Kyle Gontjes"
date: '`r Sys.Date()`'
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

# Environment
```{r environment, echo=T, message=T, include=T, results=T}
#Packages
packages <- c("tidyverse","phyloAMR")   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))  
# Print
Sys.info()
sessionInfo() 
``` 

# Load data
```{r} 
df <- readRDS("./data/regression/regression_df.RDS") 
eligible_variables <- readLines("./data/regression/eligible_variables.txt") 
```

# Purposeful selection algorithm
## Without confounding (i.e., set confounding_criteria to a very high number)  
```{r} 
purposeful_output <-  phyloaware_regression(trait = 'blbli_dich_num',variables =eligible_variables,df=df,first_present=T,patient_id="Patient_ID",culture_date="Cx_date",multivariable='purposeful',stepwise_direction = NULL,entry_criteria = 0.20,retention_criteria = 0.1,confounding_criteria = 1000e100)

saveRDS(purposeful_output,"./data/regression/purposeful_regression_results.RDS")
```
