---
title: "Figure 5: Experimental evolution of meropenem-vaborbactam resistance"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE,error=F,comment=NA)  
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","cowplot","ggtree","cowplot","ggtext","grid",'reshape2')

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))
source("./lib/consistent_themes.R")
source("./lib/common_functions.R")
```

# Load data

```{r}
df <- readRDS("./data/dataset/df.RDS")

# Canonical
canonical <- readRDS("./data/carbapenem_resistance_panel/carbapenem_resistance_panel_matrix.RDS")
df <- left_join(df,canonical)

# tn4401 data
tn4401 <- readRDS("./data/TETyper/TETyper_curated.RDS")  
df <- left_join(df,tn4401)

# load the kleborate
kleborate <- readRDS("./data/kleborate/kleborate_curated.RDS") %>% as.data.frame
df <- left_join(df,kleborate) 

# KPC Plasmids 
KPC_info_plasmids <- readRDS("./data/KPC_plasmid/KPC_containing_plasmids_mat.RDS") %>% as.data.frame
KPC_info_clusters <- readRDS("./data/KPC_plasmid/KPC_containing_clusters_mat.RDS") %>% as.data.frame 
KPC_containing_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_KPC")) %>% {ifelse(.=="KPC Plasmid",1,0)} %>% as.data.frame%>% select_if(colSums(.)>0)
KPC_clusters <- colnames(KPC_containing_clusters)
Non_KPC_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_non_KPC")) %>% {ifelse(.=="Non-KPC plasmid",1,0)} %>% as.data.frame %>% select_if(colSums(.)>0)
df <- left_join(df,KPC_containing_clusters %>% mutate(isolate_no = rownames(.))) %>% left_join(Non_KPC_clusters %>% mutate(isolate_no = rownames(.)))  
df$KPC_plasmid <- lapply(df$isolate_no,FUN=function(x){
  KPC_containing_clusters[rownames(KPC_containing_clusters) == x,] %>% select_if(colSums(.)>0) %>% colnames() %>% {ifelse(length(.)==0,"None",paste0(.,collapse=" + "))}})  %>% unlist

# Isolate list (in general order)
isolate_ranking <- readRDS("./data/evolution_experiment/growth_curve/mean_AUC_isolate_ranking.RDS")
```

## MVB selection experiment data

```{r}
MVB_evolution_data <- read_csv("./data/evolution_experiment/curated_MVB_evolution_experiment_data.csv")
```

# Create annotated evolution dataset

```{r}
MVB_evolution_data <- MVB_evolution_data %>% left_join(.,df %>% select(isolate_no,MVB,clade_I,PBP_any,OmpK36_L3_mutations,OmpK36GD,OmpK36TD,OmpK36_truncation_kleborate,OmpK36_non_syn,OmpK36_promoter_IS,tn4401_allele,KPC_present,KPC_type,KPC_plasmid,AA018_KPC,AA552_non_KPC))

MVB_evolution_data$category <- MVB_evolution_data %>% select(clade_I,KPC_type,OmpK36_L3_mutations,AA018_KPC,AA552_non_KPC) %>% apply(.,1,FUN=function(x){paste0(c(x["clade_I"],x["KPC_type"],names(x %>% subset(. %in% c(1)))),collapse=" + ")}) %>% gsub("OmpK36_L3_mutations",'Loop 3 insertion',.) %>% gsub("AA552_non_KPC","AA552 non-KPC plasmid",.) %>% gsub("AA018_KPC","AA018 KPC plasmid",.)  %>% gsub("+ No KPC +","",.) %>% gsub("\\+\\+","\\+",.)

MVB_evolution_data$category_simple <- ifelse(MVB_evolution_data$clade_I == "Clade II","Clade II without mutation",ifelse(MVB_evolution_data$clade_I == "Clade I" & MVB_evolution_data$OmpK36_L3_mutations==1,"Clade I with Loop 3 insertion","Clade I without Loop 3 insertion" ))
```

# Ranking isolates 

```{r}  
MVB_evolution_data$category <- factor(MVB_evolution_data$category,levels = sort(MVB_evolution_data$category) %>% unique())
MVB_evolution_data <- MVB_evolution_data %>% arrange(clade_I,category) 
MVB_evolution_data$isolate_no <- factor(MVB_evolution_data$isolate_no,levels = MVB_evolution_data$isolate_no %>% unique) 
MVB_evolution_data$plasmid_type <- ifelse(MVB_evolution_data$AA018_KPC==1 & MVB_evolution_data$AA552_non_KPC==1, "AA018 with blaKPC + AA552 without blaKPC",
                                          ifelse(MVB_evolution_data$AA018_KPC==1 ,"AA018 with blaKPC",ifelse(MVB_evolution_data$AA552_non_KPC==1,"AA552 without blaKPC","Other blaKPC plasmid")))

get_category_levels_using_isolate_ranking <- function(MVB_evolution_data,isolate_ranking){
  categories <- c("Clade I with Loop 3 insertion", 
                  "Clade I without Loop 3 insertion",
                  "Clade II without mutation")
  lapply(categories,FUN=function(x){
    isolates <- subset(MVB_evolution_data,category_simple ==x) %>% group_by(isolate_no) %>% summarise(median_MVB_ratio = median(log10(MVB_ratio))) %>% arrange(-median_MVB_ratio) %>% .$isolate_no %>% unique %>% as.character()
    isolates
  }) %>% unlist
}
  level <- get_category_levels_using_isolate_ranking(MVB_evolution_data,isolate_ranking)
  
saveRDS(level,"./data/evolution_experiment/median_log10_MVB_ratio_isolate_ranking.RDS")
  
MVB_evolution_data$isolate_no <- factor(MVB_evolution_data$isolate_no,levels = rev(level))
MVB_evolution_data$MVB_ratio_log_10 <- log10(MVB_evolution_data$MVB_ratio)
```

# A. Frequency data

```{r}  
A <- ggplot(data=MVB_evolution_data,aes(y=isolate_no,x=MVB_ratio,fill=category_simple),alpha=0.85) + geom_boxplot(aes(color=plasmid_type),outliers = F)   + plasmid_fill +  status_fill + ggnewscale::new_scale_color() + geom_jitter(aes(y=isolate_no,x=MVB_ratio,color=over_LoD),width=0,height = 0.25)  + theme_bw_me + ylab(NULL) + xlab("Frequency of resistance") +
    scale_x_log10(
        limits = c(5e-13, 3e-6),
        breaks = c(1e-12, 1e-10, 1e-8,1e-6),
        labels = c("10<sup>-12</sup>","10<sup>-10</sup>","10<sup>-8</sup>","10<sup>-6</sup>")
    )  + Limit_scale + theme(legend.position='bottom',legend.title.position = 'top',axis.text.x = element_markdown(size=12),legend.title = element_text(size=12),legend.text = element_markdown(size=10),axis.text.y = element_text(size=14),axis.title.x = element_text(size=14),axis.line.y = element_blank())
A
``` 

# B. Evolution genotypic data results
```{r}
table_2 <- readRDS("./tables/table_2_evolved_changes.RDS")

table_2_mutations <- table_2$`Evolved chromosomal carbapenem resistance mutation (gene [mutation]; position)` %>% unlist %>% unique %>% str_split(.,"&") %>% unlist %>% trimws %>% subset(.!='')
OmpK36_mutations <- table_2_mutations %>% subset(grepl("ompK36",x = table_2_mutations) & !grepl("upstream",x=table_2_mutations))
names(OmpK36_mutations) <- sapply(OmpK36_mutations,FUN=function(y){
  ifelse(grepl(pattern = "dup",x = y),"Duplication",
         ifelse(grepl("del",x=y),"Deletion",
         ifelse(grepl("IS",x=y),"Insertion sequence","")))
}) 

intergenic_OmpK36_mutations <-  table_2_mutations %>% subset(grepl("ompK36",x = table_2_mutations) & grepl("upstream",x=table_2_mutations))
names(intergenic_OmpK36_mutations) <- sapply(intergenic_OmpK36_mutations,FUN=function(y){
  ifelse(grepl(pattern = "dup",x = y),"Duplication",
         ifelse(grepl("del",x=y),"Deletion",
         ifelse(grepl("IS",x=y),"Insertion sequence","")))
}) 
other_mutations <- subset(table_2_mutations,!table_2_mutations %in% c(OmpK36_mutations,intergenic_OmpK36_mutations))

table_2$OmpK36_mutation <-  sapply(table_2$`Evolved chromosomal carbapenem resistance mutation (gene [mutation]; position)` ,FUN=function(name){
  canonical_mutations <- name %>% unlist %>% unique %>% str_split(.,"&") %>% unlist %>% trimws %>% subset(.!='')
  if(sum(canonical_mutations %in% OmpK36_mutations)>0){
      in_ompK36_mutation <- subset(canonical_mutations,canonical_mutations %in% OmpK36_mutations)
      result <- OmpK36_mutations %>% subset(OmpK36_mutations %in% in_ompK36_mutation) %>% names %>% paste0(collapse=" & ")
    } else {
    result <- "None"
  }
  return(result)
})

table_2$OmpK36_intergenic_mutation <-  sapply(table_2$`Evolved chromosomal carbapenem resistance mutation (gene [mutation]; position)` ,FUN=function(name){
  canonical_mutations <- name %>% unlist %>% unique %>% str_split(.,"&") %>% unlist %>% trimws %>% subset(.!='')
  if(sum(canonical_mutations %in% intergenic_OmpK36_mutations)>0){
      intergeniB_ompK36_mutation <- subset(canonical_mutations,canonical_mutations %in% intergenic_OmpK36_mutations)
      result <- intergenic_OmpK36_mutations %>% subset(intergenic_OmpK36_mutations %in% intergeniB_ompK36_mutation) %>% names %>% paste0(collapse=" & ")
    } else {
    result <- "None"
  }
  return(result)
})

table_2$other_canonical_mutations <-sapply(table_2$`Evolved chromosomal carbapenem resistance mutation (gene [mutation]; position)` ,FUN=function(name){
  canonical_mutations <- name %>% unlist %>% unique %>% str_split(.,"&") %>% unlist %>% trimws %>% subset(.!='')
  if(sum(canonical_mutations %in% other_mutations)>0){
      other_found_mutations <- subset(canonical_mutations,canonical_mutations %in% other_mutations)
      result <- other_mutations %>% subset(other_mutations %in% other_found_mutations) %>% names %>% paste0(collapse=" & ")
    } else {
    result <- "None"
  }
  return(result)
})
  
non_evolved <- MVB_evolution_data$isolate_no %>% subset(!. %in% table_2$Parent) %>% unique %>% as.character

non_evolved_df <- data.frame(Parent = non_evolved)
table_2 <- bind_rows(table_2,non_evolved_df)
table_2$Parent <- factor(table_2$Parent, levels = rev(level)) 
table_2$Sequenced <- ifelse(!table_2$Parent %in% c(non_evolved) , "Yes","No")
table_2$evolved_blaKPC_plasmid <- ifelse(table_2$`Evolved blaKPC plasmid` %in% c("AA018","AA552"), table_2$`Evolved blaKPC plasmid`,
                                         ifelse(table_2$Sequenced =="Yes", "Other plasmid",NA))
table_2$parent_blaKPC_plasmid <- ifelse(table_2$`Parental blaKPC plasmid` %in% c("AA018","AA552"), table_2$`Parental blaKPC plasmid`,
                                         ifelse(table_2$Sequenced =="Yes", "Other plasmid",NA))
melted_dataset <- reshape2::melt(table_2,id.vars = 'Parent') 
melted_dataset <- subset(melted_dataset,variable %in% c('Sequenced','parent_blaKPC_plasmid','evolved_blaKPC_plasmid','Log2 fold change in blaKPC gene CN','Log2 fold change in blaKPC plasmid CN','OmpK36_mutation',"OmpK36_intergenic_mutation"))
melted_dataset$variable <- factor(melted_dataset$variable,levels = c('Sequenced','parent_blaKPC_plasmid','evolved_blaKPC_plasmid','Log2 fold change in blaKPC gene CN','Log2 fold change in blaKPC plasmid CN','OmpK36_mutation',"OmpK36_intergenic_mutation")) 

melted_dataset$variable <- recode(melted_dataset$variable,
                                  "parent_blaKPC_plasmid" = "Parental <i>bla</i><sub>KPC</sub> plasmid", 
                                  "evolved_blaKPC_plasmid" = "Evolved <i>bla</i><sub>KPC</sub> plasmid",
                                  "Log2 fold change in blaKPC gene CN" = "<i>bla</i><sub>KPC</sub> gene <br>copy number change",
                                  "Log2 fold change in blaKPC plasmid CN" = "<i>bla</i><sub>KPC</sub> plasmid <br>copy number change",
                                  "OmpK36_mutation" = "Evolved mutation in <i>ompK36</i>",
                                  "OmpK36_intergenic_mutation" = "Evolved mutation in <br>5' intergenic region of <i>ompK36</i>")

no_sequencing <- melted_dataset %>% subset(value=="No" & variable == "Sequenced" ) %>% .$Parent %>% unique() %>% as.character

B_initial<- ggplot(melted_dataset,aes(x=variable,y=Parent)) +  
  # Parental KPC plasmid status
  geom_tile(data = subset(melted_dataset, variable %in% c("Evolved <i>bla</i><sub>KPC</sub> plasmid","Parental <i>bla</i><sub>KPC</sub> plasmid")) %>% arrange(desc(variable)),
            aes(fill = value,x=variable,y=Parent),colour = 'white',linewidth = 0.25,inherit.aes = F) +  plasmid_fill_other_key_border +   ggnewscale::new_scale_fill() + 
  # KPC copy number data
  geom_tile(data = subset(melted_dataset, variable %in% c('<i>bla</i><sub>KPC</sub> gene <br>copy number change','<i>bla</i><sub>KPC</sub> plasmid <br>copy number change')),
            aes(fill = as.numeric(value)),colour = 'white',linewidth = 0.25) +  scale_fill_gradient2(low = "blue", mid = "white" ,high = "red",name = expression(Log[2]~"fold change"),midpoint=1,na.value = 'white',guide = guide_colorbar(order=3),limits=c(0,8)) + ggnewscale::new_scale_fill() + 
  # Mutation data
  geom_tile(data = subset(melted_dataset, variable %in% c("Evolved mutation in <i>ompK36</i>","Evolved mutation in <br>5' intergenic region of <i>ompK36</i>")),
            aes(fill=value),colour = 'white',linewidth = 0.25) + theme(axis.text.x = element_markdown(angle=270,hjust = 0,vjust = 0.5),panel.border  = element_blank(),panel.grid = element_blank())  + mutation_scale +  
  # Remaining themes
  ylab(NULL) + xlab(NULL) +
    scale_x_discrete(expand = c(0, 0)) +
    scale_y_discrete(expand = c(0, 0)) + theme(axis.text = element_markdown(size=12),plot.background = element_rect(color = 'white'),legend.key.spacing.y = unit(0.05,'cm'))  + geom_text(
        data = subset(
            melted_dataset,
            variable != "Sequenced" &
                Parent %in% no_sequencing
        ),
        aes(x = variable, y = Parent),
        label = "X",
        size = 3
    )  
```

# Combined figure

```{r,fig.width=10.5,fig.height=5.25}
A + theme(legend.position = 'right')
``` 

```{r,fig.width=11,fig.height=7.3333}
B_initial
```

```{r,fig.width=12.5,fig.height=7.5}
A_fig <-  cowplot::plot_grid(NULL,A + theme(axis.ticks.y = element_blank(),axis.text.y = element_text(size=0)),NULL,ncol=1,rel_heights = c(0.03,1,0.055))
 
B <- cowplot::plot_grid(NULL,B_initial  + theme(legend.position = 'none'),NULL,ncol=1,rel_heights = c(0.034,1,0.0375))

legend_B <- cowplot::get_legend(B_initial) 

figure <- cowplot::plot_grid(A_fig,
                             B,
                             legend_B,
                             ncol=3,
                             labels = c("A","B",""),
                             rel_widths = c(1,0.55,0.19),
                             rel_heights = c(1,1,1),
                             label_size = 16)

figure 
```

# Save figure

```{r}
ggsave("./figures/figure_5_experimental_evolution.png",figure,dpi=900,width=12.5,height=7,bg='white')
```
