---
title: "Figure 2: Differences in β-lactam/β-lactamase inhibitor combination resistance across clades of epidemic lineage sequence type 258"
author: "Kyle Gontjes"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE)  
knitr::opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/') 
```

# Environment

```{r}
packages <- c("tidyverse","kableExtra","tableone","cowplot")
lapply(packages,library,character.only=T)

# functions
source("./lib/common_functions.R")
source("./lib/consistent_themes.R")
source("./scripts/figures/figure_2_functions.R")
```

# Load data

```{r}
df <- readRDS("./data/dataset/df.RDS")
pclustering <- readRDS("./data/asr_clustering/blbli_asr_clustering_df.RDS") 

df <- df %>% left_join(.,pclustering %>% select(isolate_no,blbli_asr_cluster_renamed) %>% `colnames<-`(c("isolate_no","blbli_asr_cluster_renamed"))) 

rownames(df) <- df$isolate_no

df$blbli_clustering_simple <- recode(df$blbli_asr_cluster_renamed,"No feature"="Susceptible") 
```

# Part 1 - MIC Histogram

```{r} 
# Max value
max_value <- max(c(table(df$IR_log_2),table(df$MVB_log_2)))
max_ylim_ceiling <- (ceiling(max_value /10) *10) + 10
MIC_y_scale <- scale_y_continuous(breaks =  seq(0, max_ylim_ceiling, by = 50),limits = c(0,max_ylim_ceiling))

# Get median values
add_clade_median_values <- function(dataframe, variable, clade_variable,max_value) {
  clade_I_median <- dataframe[dataframe[[clade_variable]] == "Clade I", variable] %>% median(na.rm = TRUE)
  clade_II_median <- dataframe[dataframe[[clade_variable]] != "Clade I", variable] %>% median(na.rm = TRUE)
  
  list(clade_I = annotate('point',  x = clade_I_median, y = max_ylim_ceiling,  fill =  clade_colors[["Clade I"]], color = clade_colors[["Clade I"]], shape = 25,  size = 2.5), 
       clade_II = annotate('point',  x = clade_II_median, y = max_ylim_ceiling,  fill =  clade_colors[["Clade II"]],color = clade_colors[["Clade II"]], shape = 25,  size = 2.5))
}

IR_intercepts <-  add_clade_median_values(df, "IR_log_2", "clade_I")
MVB_intercepts <-  add_clade_median_values(df, "MVB_log_2", "clade_I")

# Imipenem-relebactam
fig2a <- create_MIC_histogram(df$IR_log_2,df$clade_I,"Imipenem-relebactam") + figure_2_format + MIC_IR_x_scale + MIC_y_scale +  IR_intercepts[['clade_I']] + IR_intercepts[['clade_II']]  + clade_colors_scale_3_col  

# Meropenem-vaborbactam
fig2c <- create_MIC_histogram(df$MVB_log_2,df$clade_I,"Meropenem-vaborbactam")   +figure_2_format + MIC_MVB_x_scale + MIC_y_scale + MVB_intercepts[['clade_I']] + MVB_intercepts[['clade_II']] + clade_colors_scale_3_col
```

# Part 2 - Resistance categories

## Generate the proportion data

```{r}
IR_clade_prop <- df %>% group_by(clade_I,IR_cat)  %>%
  dplyr::summarise(n = n()) %>%
  mutate(freq = n / sum(n)*100) %>% `colnames<-`(c("clade_I","phenotype_cat","n","freq"))

MVB_clade_prop <- df %>% group_by(clade_I,MVB_cat)  %>%
  dplyr::summarise(n = n()) %>%
  mutate(freq = n / sum(n) *100) %>% `colnames<-`(c("clade_I","phenotype_cat","n","freq"))
```

```{r}
# Imipenem-relebactam
fig2d <- MIC_prop_hist(IR_clade_prop) + resistance_cat_scale_v + figure_2_format 

# Meropenem-vaborbactam
fig2b <- MIC_prop_hist(MVB_clade_prop) + resistance_cat_scale_v + figure_2_format 
```

# Part 3 - Phylogenetic clustering of resistance

```{r}
# Generate clustering across clades
blbli_clade_phylo_prop <- df %>% subset(blbli_clustering_simple != "Susceptible") %>% group_by(clade_I,blbli_clustering_simple)  %>% 
  dplyr::summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>% `colnames<-`(c("clade_I","phenotype_cat","n","freq"))  
 
blbli_clade_phylo_prop$phenotype_cat <- factor(blbli_clade_phylo_prop$phenotype_cat,levels = c("Singleton",subset(blbli_clade_phylo_prop$phenotype_cat,blbli_clade_phylo_prop$phenotype_cat != "Singleton") %>% sort))

# Figure 3E (BL/BLI resistance clustering across clades)
fig2e <- MIC_prop_hist_count(blbli_clade_phylo_prop) + cluster_scale + figure_2_format  + ylab("Resistant isolates")
```

# Figure Compilation

```{r,message=F,echo=F,error=F,warning=F,fig.width=20,fig.height=12.5}
# Merge figures together
fig2_data <- cowplot::plot_grid(fig2a + theme(legend.position = "none"),
                                fig2b  + theme(legend.position = "none"),"",
                                fig2c + theme(legend.position = "none"),
                                fig2d + theme(legend.position = "none") , 
                                fig2e + theme(legend.position = "none"),
                                ncol=3,
                                rel_widths = c(1,0.45,0.45,1,0.45,0.45),
                                labels = c("A","B","","C","D","E"),label_size = 18)

# Create legend
clade_legend <- cowplot::get_legend(fig2a)
resistance_legend <- cowplot::get_legend(fig2b)
clade_phylo_legend <- cowplot::get_legend(fig2e)

fig2.legends <- cowplot::plot_grid(clade_legend,"",resistance_legend,"",clade_phylo_legend,ncol=5,align = "hv",rel_widths = c(1,.0025,1,0.25,1)) + theme(plot.margin = unit(c(t=-2.5, 2, b=-1,0 ), "cm"))
 
# Add legend to figure
figure_2 <-  cowplot::plot_grid(fig2_data,fig2.legends,ncol=1,rel_heights = c(1,0.18),align = "h")
```

# Figure

```{r,message=F,echo=F,error=F,warning=F,fig.width=9.5,fig.height=7.6}
figure_2
```

## Save figure

```{r}
ggsave(plot = figure_2, filename = './figures/figure_2.png', width = 9.5, height = 7.6,bg = 'white', dpi=900)
```