---
title: "Supplemental Figure 13: AA552 dynamics and BL/BLI dynamics"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

# Environment

```{r}
packages <- c("tidyverse","cowplot","ggtree","ape","phytools","gridExtra","kableExtra","colorRamp2","RColorBrewer","ComplexHeatmap",'phyloAMR')

# Load packages
invisible(lapply(packages,library,character.only=T,quietly=T))
source("./lib/common_functions.R")
source("./lib/consistent_themes.R")
source("./scripts/GWAS/analysis/GWAS_analysis_scripts.R") 

# Set null device
set_null_device("png")
```

# Load data

```{r} 
# Standard data
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile")
# GWAS table
gwas_table <- readRDS("./data/GWAS/hits/gwas_hits_table.RDS") %>% subset(nn_qc=="Pass")
gwas_mat <- readRDS("./data/GWAS/hits/gwas_mat.RDS")  
# Matrices
## Kleborate matrix
kleborate <- readRDS("./data/GWAS/matrices/kleborate_mat.RDS") %>% as.data.frame 
## KPC Plasmids 
KPC_containing_clusters <- readRDS("./data/GWAS/matrices/KPC_containing_cluster_mat.RDS") %>% as.data.frame 
## BLBLI clustering
pclustering <- readRDS("./data/asr_clustering/blbli_asr_clustering_df.RDS")
blbli_asr <- readRDS("./data/asr_clustering/blbli_asr.RDS") 
# Join
df <- left_join(df,kleborate %>% mutate(isolate_no = rownames(.)))
df <- left_join(df,KPC_containing_clusters %>% mutate(isolate_no = rownames(.)))  
df <- left_join(df,pclustering %>% select(isolate_no,blbli_asr_cluster_renamed))
df$blbli_asr_cluster_renamed_simple <- recode(df$blbli_asr_cluster_renamed,"No feature"="Susceptible" )

# KPC plasmids 
KPC_info_clusters <- readRDS("./data/KPC_plasmid/KPC_containing_clusters_mat.RDS") %>% as.data.frame 
KPC_containing_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_KPC")) %>% {ifelse(.=="KPC Plasmid",1,0)} %>% as.data.frame%>% select_if(colSums(.)>0)
KPC_clusters <- colnames(KPC_containing_clusters)
Non_KPC_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_non_KPC")) %>% {ifelse(.=="Non-KPC plasmid",1,0)} %>% as.data.frame %>% select_if(colSums(.)>0)
df <- left_join(df,KPC_containing_clusters %>% mutate(isolate_no = rownames(.))) %>% left_join(Non_KPC_clusters %>% mutate(isolate_no = rownames(.)))
    
 
df$AA525_status_md <- ifelse(df$AA552_KPC ==1, "AA552 <i>bla</i><sub>KPC</sub> plasmid",ifelse(df$AA552_non_KPC ==1,"AA552 Non-<i>bla</i><sub>KPC</sub> plasmid","Other")) %>% factor(.,levels = c("AA552 <i>bla</i><sub>KPC</sub> plasmid","AA552 Non-<i>bla</i><sub>KPC</sub> plasmid","Other"))

df$AA525_status <- gsub("<i>bla</i><sub>KPC</sub>","blaKPC",df$AA525_status_md)
   
df$blbli_asr_cluster_renamed_simple <- recode(df$blbli_asr_cluster_renamed,"No feature"="Susceptible" )
``` 

# Status over time

```{r}
df$date <- lubridate::as_date(df$Cx_date) 
# Number of weeks using date data
number_of_weeks <- as.numeric(round(difftime(max(df$Cx_date),min(df$Cx_date),units = 'weeks')) + 1)
 
AA552_scale <- scale_fill_manual(values = c("blue",'lightblue','lightgray'), breaks = c("AA552 <i>bla</i><sub>KPC</sub> plasmid","AA552 Non-<i>bla</i><sub>KPC</sub> plasmid","Other"),name="AA552 Status")
AA552_scale_color <- scale_color_manual(values = c("blue",'lightblue','lightgray'), breaks = c("AA552 <i>bla</i><sub>KPC</sub> plasmid","AA552 Non-<i>bla</i><sub>KPC</sub> plasmid","Other"),name="AA552 Status")

A <- ggplot(data=df,aes(x=Cx_date,fill=AA525_status_md)) + geom_histogram(bins = number_of_weeks) + theme_bw_me + xlab("Collection date") + ylab ("Isolates") + scale_y_continuous(limits = c(0, 20))  + theme_bw_me + theme(legend.position='none') + AA552_scale

A
```

# Temporal distribution

```{r}
B <-   ggplot(data=df,aes(x=Cx_date,fill=AA525_status_md,y=AA525_status_md)) + geom_boxplot(alpha=0.75,outliers=F) + geom_jitter(mapping = aes(color=as.factor(blbli_asr_cluster_renamed_simple)),alpha=1,width = 0,height = 0.25) + theme_bw_me + xlab("Collection date") + ylab("")   + theme(legend.position = 'none')  + theme_bw_me + theme(legend.position='none') +  AA552_scale + cluster_scale_gray_color + theme(axis.text.y = element_markdown())

B
```

# Temporal distribution of BL/BLI resistant clusters

```{r}
C <-   ggplot(data=df,aes(x=Cx_date,fill=blbli_asr_cluster_renamed_simple)) + geom_histogram(bins = number_of_weeks) + theme_bw_me + xlab("Collection date") + ylab ("Isolates") + scale_y_continuous(limits = c(0, 20))  + theme_bw_me + theme(legend.position='none') + cluster_scale_gray

D <-   ggplot(data=df,aes(x=Cx_date,y=as.factor(blbli_asr_cluster_renamed_simple),fill=blbli_asr_cluster_renamed_simple)) + geom_boxplot(alpha=.75,outliers=F) + geom_jitter(mapping = aes(color=as.factor(AA525_status)),alpha=1,width = 0,height = 0.25) + theme_bw_me + xlab("Collection date") + ylab("")   + theme(legend.position = 'none')  + theme_bw_me + theme(legend.position='none') +  cluster_scale_gray + AA552_scale_color 

C
```

# Heatmap

# Facility plot
```{r}
phenotype = 'AA525_status'
  dataframe <- df
  dataframe$clustering <- as.factor(dataframe[[phenotype]])
  
  matrix_raw <- dataframe %>%
    group_by(LTACH_Recode, clustering) %>%
    summarise(n = n(), .groups = "drop") %>%
    tidyr::pivot_wider(
        names_from = LTACH_Recode,
        values_from = n,
        values_fill = 0  
    ) %>% column_to_rownames(var='clustering')

  matrix_raw_ordered <- matrix_raw[match(rev(levels(dataframe$clustering)),rownames(matrix_raw),incomparables = F) %>% subset(is.na(.)==F),]

  rownames(matrix_raw_ordered) <- paste0(rownames(matrix_raw_ordered)," (n = ",rowSums(matrix_raw_ordered),")") 
  mat_prop <- sweep(matrix_raw_ordered, 1, rowSums(matrix_raw_ordered), FUN = "/")   
  max(rownames(mat_prop) %>% nchar()) 
  shared_rn_width <- unit(5, "in")
  
  fig <- ComplexHeatmap::Heatmap(matrix = mat_prop,
    col = c("white", "red"),
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    cell_fun = function(j, i, x, y, width, height, fill) {
       val <- matrix_raw_ordered[i, j] 
    if (val != 0) {
    grid.text(sprintf("%.2s", val), x, y, gp = gpar(fontsize = 14))
    }
    },
    show_heatmap_legend = FALSE,
    column_names_rot = 0,
    column_title = "Facility",
    column_title_side = "bottom",
    width = ncol(mat_prop) * unit(.4, "in"),
    height = nrow(mat_prop) * unit(.2, "in"),
    column_names_centered = TRUE,
    row_names_centered = FALSE,
    row_names_max_width = shared_rn_width,
    row_names_gp = gpar(fontsize = 14))
     
heatmap_for_cowplot  <-    grid.grabExpr(draw(fig)) 

# Add margin to this
E <- cowplot::plot_grid(heatmap_for_cowplot)

E
```

# Spatiotemporal overall

```{r}
df$blbli_asr_cluster_renamed_simple_recode <- factor(df$blbli_asr_cluster_renamed_simple,levels = rev(c("Susceptible","Singleton",paste0("Cluster ",1:7))),labels = rev(c("Susceptible","Singleton",paste0("Cluster ",1:7))))

phenotype = 'blbli_asr_cluster_renamed_simple_recode'
  dataframe <- df
  dataframe$clustering <- as.factor(dataframe[[phenotype]])
  
  matrix_raw <- dataframe %>%
    group_by(LTACH_Recode, clustering) %>%
    summarise(n = n(), .groups = "drop") %>%
    tidyr::pivot_wider(
        names_from = LTACH_Recode,
        values_from = n,
        values_fill = 0  
    ) %>% column_to_rownames(var='clustering')

  matrix_raw_ordered <- matrix_raw[match(rev(levels(dataframe$clustering)),rownames(matrix_raw),incomparables = F) %>% subset(is.na(.)==F),]

  rownames(matrix_raw_ordered) <- paste0(rownames(matrix_raw_ordered)," (n = ",rowSums(matrix_raw_ordered),")")

  mat_prop <- sweep(matrix_raw_ordered, 1, rowSums(matrix_raw_ordered), FUN = "/")  
  
  fig <- ComplexHeatmap::Heatmap(matrix = mat_prop,
    col = c("white", "red"),
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    cell_fun = function(j, i, x, y, width, height, fill) {
       val <- matrix_raw_ordered[i, j] 
    if (val != 0) {
    grid.text(sprintf("%.2s", val), x, y, gp = gpar(fontsize = 14))
    }
    },
    show_heatmap_legend = FALSE,
    column_names_rot = 0,
    column_title = "Facility",
    column_title_side = "bottom",
    width = ncol(mat_prop) * unit(.4, "in"),
    height = nrow(mat_prop) * unit(.2, "in"),
    column_names_centered = TRUE,
    row_names_centered = FALSE,
    row_names_max_width = shared_rn_width,
  row_names_gp = gpar(fontsize = 14)) 
    

heatmap_for_cowplot  <-    grid.grabExpr(draw(fig)) 

# Add margin to this
f <- cowplot::plot_grid(heatmap_for_cowplot)

f
```

# Temporal distribution facilities

```{r}
G <- ggplot(data=df,aes(x=Cx_date,y=as.factor(blbli_asr_cluster_renamed_simple))) + geom_boxplot(alpha=0.5,outliers=F) + geom_jitter(mapping = aes(color=AA525_status_md),alpha=1,width = 0,height = .25,size=1.2) + theme_bw_me + xlab("Collection date") + ylab("")   + theme(legend.position = 'none')  + theme_bw_me + theme(legend.position='none') +  AA552_scale + AA552_scale_color + facet_wrap(~LTACH_Recode,ncol=4)

G
```

# Curate figure
```{r,fig.height=17,fig.width=13.6}
AB <- cowplot::plot_grid(A,B,labels = c("A",'B'),ncol=2)
CD <- cowplot::plot_grid(C,D,labels = c("C",'D'),ncol=2)
figure <- cowplot::plot_grid(AB,CD,E,f,G,labels = c("","","E","F","G"),ncol=1,rel_heights = c(.275,.275,.175,.325,1))
figure
```

# Save figure
```{r,fig.height=20,fig.width=10}
ggsave("./figures/s_figure_13_spatiotemporal_distribution_BLBLI_AA552.png", plot = figure, units='in', height=17, width=13.6, dpi=900, bg='white')
```

# Patient summaries
## No evidence of within patient transfer
## Some susceptible + resistant strain pairs within patients!
```{r}
KPC_plasmid_summaries <-  df %>% group_by(Patient_ID) %>% summarise(n=n(),blbli_dich_num=sum(blbli_dich_num),AA552_KPC= sum(AA552_KPC),AA018_KPC=sum(AA018_KPC),AA552_non_KPC=sum(AA552_non_KPC)) %>% mutate(blbli_sus = n - blbli_dich_num )

KPC_plasmid_summaries$blbli_both <- KPC_plasmid_summaries$blbli_dich_num>0 & KPC_plasmid_summaries$blbli_sus >0

KPC_plasmid_summaries$AA552_KPC_AA018_KPC <- ifelse(KPC_plasmid_summaries$AA552_KPC>0 & KPC_plasmid_summaries$AA018_KPC>0,T,F)
KPC_plasmid_summaries$AA552_non_KPC_AA018_KPC <- ifelse(KPC_plasmid_summaries$AA552_non_KPC>0 & KPC_plasmid_summaries$AA018_KPC>0,T,F)

paste0("No evidence of within patient transfer: ")

table(KPC_plasmid_summaries$AA552_non_KPC_AA018_KPC,KPC_plasmid_summaries$AA552_KPC_AA018_KPC,dnn = c("AA552 non KPC & AA018 KPC isolate(s)","Have KPC on a AA552 plasmid and a KPC on AA018 plasmid across isolates"))

table(KPC_plasmid_summaries$blbli_both,dnn = c("Susceptible and resistant strain"))
```

# LR data
```{r}
paste0("Compelling case, but not one before the other!")
df %>% subset(isolate_no %in% c("PCMP_H173","PCMP_H276")) %>% select(isolate_no,LTACH_Recode,Cx_date,AA552,blbli_asr_cluster_renamed)

df %>% subset(isolate_no %in% c("PCMP_H148","PCMP_H307")) %>% select(isolate_no,LTACH_Recode,Cx_date,AA552,blbli_asr_cluster_renamed)
```
