---
title: "Supplemental figure 7"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```


```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","gridExtra",'kableExtra',"tableone","ape","ggtree","ggnewscale",'phyloAMR')

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Scripts
source("./lib/consistent_themes.R")
source("./scripts/GWAS/analysis/GWAS_analysis_scripts.R")
source("./lib/common_functions.R")  
```

```{r}
# Standard data
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile") 
pclustering <- readRDS("./data/asr_clustering/blbli_asr_clustering_df.RDS")
df <- df %>% left_join(.,pclustering)
# Matrices 
## KPC Plasmids 
KPC_info_clusters <- readRDS("./data/KPC_plasmid/KPC_containing_clusters_mat.RDS") %>% as.data.frame 
KPC_containing_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_KPC")) %>% {ifelse(.=="KPC Plasmid",1,0)} %>% as.data.frame%>% select_if(colSums(.)>0)
KPC_clusters <- colnames(KPC_containing_clusters)
Non_KPC_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_non_KPC")) %>% {ifelse(.=="Non-KPC plasmid",1,0)} %>% as.data.frame %>% select_if(colSums(.)>0)
df <- left_join(df,KPC_containing_clusters %>% mutate(isolate_no = rownames(.))) %>% left_join(Non_KPC_clusters %>% mutate(isolate_no = rownames(.)))
```

# Gain & Loss Figure
```{r}
traits_of_interest <- c("blbli_dich_num",KPC_clusters)   
trait_parent_child <- lapply(traits_of_interest,FUN=function(x){
  asr(df,tr,tip_name_var = 'isolate_no',pheno=x,model='MF') %>% .$parent_child_df
}) %>% `names<-`(traits_of_interest)

synchronous_changes_w_AA552 <- lapply(traits_of_interest %>% subset(.!="AA552_KPC"),FUN=function(x){
  phyloAMR::synchronous_detection(comparitor_parent_child_df = trait_parent_child[[x]],trait_parent_child_df = trait_parent_child[['AA552_KPC']],node_states = 'joint')
}) %>% do.call(rbind,.) %>% mutate(comparitor = traits_of_interest %>% subset(.!="AA552_KPC"))

synchronous_changes_w_AA552 %>% subset(synchronous_transitions_num>0)

AA552_gain <- trait_parent_child$AA552_KPC %>% subset(gain ==1) %>% .$child
AA018_loss <- trait_parent_child$AA018_KPC %>% subset(loss ==1) %>% .$child
AA274_loss <- trait_parent_child$AA274_KPC %>% subset(loss ==1) %>% .$child
```

```{r}
st258 <- ggtree(tr)
tree_obj <- st258   +
    geom_nodepoint(aes(fill = "AA552 KPC plasmid gain",shape="AA552 KPC plasmid gain",subset=(node %in% AA552_gain),size="AA552 KPC plasmid gain",legend=F))  +
    geom_tippoint(aes(fill = "AA552 KPC plasmid gain",shape="AA552 KPC plasmid gain",subset=(node %in% AA552_gain),size="AA552 KPC plasmid gain",legend=F)) +
    geom_nodepoint(aes(fill = "AA274 KPC plasmid loss",shape="AA274 KPC plasmid loss",subset=(node %in% AA274_loss),size="AA274 KPC plasmid loss",legend=F)) + 
    geom_tippoint(aes(fill = "AA274 KPC plasmid loss",shape="AA274 KPC plasmid loss",subset=(node %in% AA274_loss),size="AA274 KPC plasmid loss",legend=F))  +
    geom_nodepoint(aes(fill = "AA018 KPC plasmid loss",shape="AA018 KPC plasmid loss",subset=(node %in% AA018_loss),size="AA018 KPC plasmid loss",legend=F)) +
    geom_tippoint(aes(fill = "AA018 KPC plasmid loss",shape="AA018 KPC plasmid loss",subset=(node %in% AA018_loss),size="AA018 KPC plasmid loss",legend=F))  + scale_fill_manual(name="Gain/Loss Events",values = c("AA552 KPC plasmid gain" ="#91796A","AA018 KPC plasmid loss"="#97C466","AA274 KPC plasmid loss"="blue"),guide = guide_legend(title.position = "top",label.position = "bottom",ncol=1,order=1)) + 
    scale_shape_manual(name="Gain/Loss Events",values=c("AA552 KPC plasmid gain"=22,"AA018 KPC plasmid loss"=24,"AA274 KPC plasmid loss"=23),guide = guide_legend(title.position = "top",label.position = "bottom",ncol=1,order=1)) + scale_size_manual(name="Gain/Loss Events",values = c("AA552 KPC plasmid gain" =20,"AA018 KPC plasmid loss"= 16,"AA274 KPC plasmid loss"=16),guide = guide_legend(title.position = "top",label.position = "bottom",ncol=1,order=1))  
```

# A. KPC Plasmid content
```{r ,fig.height = 50, fig.width = 57.5,echo=F,message=F,error=F,warning=F}  
consistent_theme <- theme(plot.margin=grid::unit(c(-2,-3,0,-3), "cm"),legend.position = 'bottom',legend.direction="vertical", legend.justification = "center",legend.box.spacing = unit(.0001, "cm"),legend.key.size = unit(1, "cm"),legend.key.width = unit(1, "cm") , legend.title = element_text(size=68),legend.text = element_text(size=64),legend.title.align=0.5,legend.text.align = 0, legend.margin=margin(t=-5,r=0,b=0,l=0,unit="cm"),legend.spacing.x=unit(.75, "cm"))  
  
 rownames(df) <- df$isolate_no
  #Step #1: Clades
  p.1 <- gheatmap(tree_obj + ggnewscale::new_scale_fill(),df %>% select(clade_I) %>% `colnames<-`("ST258 Clade"), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 20, width = 0.1)   + clade_colors_scale_v  +   consistent_theme
  #Step #3: BL/BLI Cluster
  p.2 <- p.1 + new_scale_fill() 
  p.3 <-  gheatmap(p.2,df %>% select(blbli_asr_cluster_renamed) %>% mutate_all(as.factor) %>% `colnames<-`("BL/BLI clustering"), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 20, width = 0.1,offset =.000025) + cluster_scale + consistent_theme  
  
  #Step #4: MVB Binary
  p.4 <- p.3 + new_scale_fill()
  p.5 <-  gheatmap(p.4,df %>% select(blbli_dich,MVB_dich,IR_dich) %>% `colnames<-`(c("BL/BLI resistant","MVB resistant","IR resistant")), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 20, width = 0.3,offset =.00005) + resistance_scale + consistent_theme  
  
  #Step #6: MVB MIC
  p.6 <- p.5 + new_scale_fill()
  p.7 <-  gheatmap(p.6,df %>% select(MVB_log_2,IR_log_2) %>%   mutate_all(as.factor)  %>%`colnames<-`(c("MVB MIC","IR MIC")), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 20, width = 0.2,offset =.000125) + Log2_scale + consistent_theme  
  # Add KPC data
  p8 <- p.7 +ggnewscale::new_scale_fill()
  p9 <- gheatmap(p8,df %>% select(AA018_KPC,AA552_KPC,AA356_KPC,AA018_non_KPC,AA552_non_KPC) %>% mutate_all(as.factor) %>% `colnames<-`(c("AA018 KPC plasmid","AA552 KPC plasmid","AA356 KPC plasmid","AA018 non-KPC plasmid","AA552 non-KPC plasmid")), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 20, width = 0.5,offset =.000175) + feature_scale_v  +  consistent_theme + ylim(NA,510) 
  p9
```
 
