---
title: "s_figure_6"
output: html_document
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
---

# Combination Therapy Manuscript
```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","ggtree","ape","ggnewscale","tableone","kableExtra","cowplot",'phyloAMR')

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Scripts
source("./lib/common_functions.R")
source("./lib/consistent_themes.R")
```

# Data
```{r}
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile")
pclustering <- readRDS("./data/asr_clustering/blbli_asr_clustering_df.RDS")

KPC_plasmid_depth <- readRDS("./data/KPC_coverage/normalized/KPNIH1_KPC_plasmid_depth_by_feature_median_chromosome_normalized.RDS")
KPC_plasmid_depth$isolate_no <- rownames(KPC_plasmid_depth)
                                         
KPC_gene_depth <- KPC_plasmid_depth %>% select(isolate_no,KPNIH1_RS28775_chr_median_norm)

# Matrices 
## KPC Plasmids 
KPC_info_clusters <- readRDS("./data/KPC_plasmid/KPC_containing_clusters_mat.RDS") %>% as.data.frame 
KPC_containing_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_KPC")) %>% {ifelse(.=="KPC Plasmid",1,0)} %>% as.data.frame%>% select_if(colSums(.)>0)
KPC_clusters <- colnames(KPC_containing_clusters)
Non_KPC_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_non_KPC")) %>% {ifelse(.=="Non-KPC plasmid",1,0)} %>% as.data.frame %>% select_if(colSums(.)>0)
df <- left_join(df,KPC_containing_clusters %>% mutate(isolate_no = rownames(.))) %>% left_join(Non_KPC_clusters %>% mutate(isolate_no = rownames(.))) %>% left_join(pclustering)  %>% left_join(.,KPC_gene_depth)
```

# Gain & Loss Figure
```{r}
df_CI <- df %>% subset(clade_I == 'Clade I') %>% as.data.frame()
rownames(df_CI) <- df_CI$isolate_no
tr_CI <- tr %>% keep.tip(df_CI$isolate_no)
KPC_clusters_in_CI <- df_CI %>% select(KPC_clusters) %>% colSums() %>% subset(.>0) %>% names

traits_of_interest <- c("blbli_dich_num",KPC_clusters_in_CI)   
trait_parent_child <- pbmcapply::pbmclapply(traits_of_interest,FUN=function(x){
  asr(df_CI,tr_CI,tip_name_var = 'isolate_no',trait=x,model='MF') %>% .$parent_child_df
},mc.cores=5) %>% `names<-`(traits_of_interest)

synchronous_changes_w_AA552 <- pbmcapply::pbmclapply(traits_of_interest %>% subset(.!="AA552_KPC"),FUN=function(x){
  phyloAMR::synchronous_transitions(comparitor_parent_child_df = trait_parent_child[[x]],trait_parent_child_df = trait_parent_child[['AA552_KPC']],node_states = 'joint')
},mc.cores=5) %>% do.call(rbind.data.frame,.) %>% mutate(comparitor = traits_of_interest %>% subset(.!="AA552_KPC"))

synchronous_changes_w_AA552 %>% subset(synchronous_transitions_num>0)

AA552_gain <- trait_parent_child$AA552_KPC %>% subset(gain ==1) %>% .$child
AA018_loss <- trait_parent_child$AA018_KPC %>% subset(loss ==1) %>% .$child 
```

```{r}
CI_tree <- ggtree(tr_CI)
tree_obj <- CI_tree   +
    geom_nodepoint(aes(fill = "AA552 KPC plasmid gain",shape="AA552 KPC plasmid gain",subset=(node %in% AA552_gain),size="AA552 KPC plasmid gain",legend=F))  +
    geom_tippoint(aes(fill = "AA552 KPC plasmid gain",shape="AA552 KPC plasmid gain",subset=(node %in% AA552_gain),size="AA552 KPC plasmid gain",legend=F))   +
    geom_nodepoint(aes(fill = "AA018 KPC plasmid loss",shape="AA018 KPC plasmid loss",subset=(node %in% AA018_loss),size="AA018 KPC plasmid loss",legend=F)) +
    geom_tippoint(aes(fill = "AA018 KPC plasmid loss",shape="AA018 KPC plasmid loss",subset=(node %in% AA018_loss),size="AA018 KPC plasmid loss",legend=F))  + scale_fill_manual(name="Gain/Loss Events",values = c("AA552 KPC plasmid gain" ="#91796A","AA018 KPC plasmid loss"="#97C466"),guide = guide_legend(title.position = "top",label.position = "bottom",ncol=1,order=1)) + 
    scale_shape_manual(name="Gain/Loss Events",values=c("AA552 KPC plasmid gain"=22,"AA018 KPC plasmid loss"=24),guide = guide_legend(title.position = "top",label.position = "bottom",ncol=1,order=1)) + scale_size_manual(name="Gain/Loss Events",values = c("AA552 KPC plasmid gain" =6,"AA018 KPC plasmid loss"= 3.5),guide = guide_legend(title.position = "top",label.position = "bottom",ncol=1,order=1))  
```

# Figure A  

```{r,fig.height=10,fig.width=11}
# Phylogeny of KPC-containing plasmid across Clade I
df_CI <- df %>% subset(clade_I == "Clade I")
rownames(df_CI) <- df_CI$isolate_no
tr_CI <- keep.tip(tr, df_CI$isolate_no) 

df_CI_KPC_plasmid_mat <- df_CI %>% select(KPC_clusters) %>% select_if(colSums(.)>0) %>% mutate(Other_KPC_cluster = ifelse(AA275_KPC ==1 |AD548_KPC==1 | AA274_KPC==1 | AA356_KPC==1 ,1,0)) %>% select(-AA275_KPC,-AD548_KPC,-AA274_KPC,-AA356_KPC)
 
df_CI_relevant_plasmids <- left_join(df_CI_KPC_plasmid_mat %>% mutate(isolate_no = rownames(.)), df_CI %>% select(isolate_no, AA552_non_KPC,AA018_non_KPC)) %>% `rownames<-`(.$isolate_no) %>% select(-isolate_no) 
  #Step #1: Clades
  tree_obj_1 <- tree_obj + ggnewscale::new_scale_fill()
  p.1 <- gheatmap(tree_obj_1,df_CI %>% select(clade_I) %>% `colnames<-`("ST258 clade"), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 8, width = 0.075)   + clade_colors_scale_v
  
  #Step #3: BL/BLI Cluster
  p.2 <- p.1 + new_scale_fill()
  p.3 <-  gheatmap(p.2,df_CI %>% select(blbli_asr_cluster_renamed) %>% mutate_all(as.factor) %>% `colnames<-`("BL/BLI clustering"), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 8, width = 0.075,offset =.0000175) + cluster_scale_4  
  
  #Step #4: MVB Binary
  p.4 <- p.3 + new_scale_fill()
  p.5 <-  gheatmap(p.4,df_CI %>% select(blbli_dich) %>% `colnames<-`(c("BL/BLI resistance")), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 8, width = 0.075,offset =.0000350) + resistance_scale 
  
  #Step #6: MVB MIC
  p.6 <- p.5 + new_scale_fill()
  p.7 <-  gheatmap(p.6,df_CI %>% select(MVB_log_2,IR_log_2) %>%   mutate_all(as.factor)  %>%`colnames<-`(c("MVB MIC","IR MIC")), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 8, width = 0.15,offset =.0000525) + Log2_scale 
   
 p.8 <- p.7 + new_scale_fill() 
A <-  gheatmap(p.8,df_CI_relevant_plasmids  %>% select(AA018_KPC,AA018_non_KPC,AA552_KPC,AA552_non_KPC,Other_KPC_cluster) %>% mutate_all(as.factor) %>% `colnames<-`(c("AA018 KPC plasmid","AA018 non-KPC plasmid","AA552 KPC plasmid","AA552 non-KPC plasmid","Other KPC plasmid")), colnames_position = "top",colnames_angle=90, colnames_offset_y = 0.25, hjust = 0, color = NA, font.size = 8, width = 0.375,offset =.0000875) + feature_scale_v   + ylim(NA,215) + theme(legend.position = 'bottom') + consistent_theme_sfigure_6
```

# B KPC copy number
```{r} 
df_CI$KPC_plasmid_simplified <- ifelse(df_CI$AA018_KPC == 1, "AA018",ifelse(df_CI$AA552_KPC == 1,"AA552","Other"))
B <- ggplot(data= df_CI) + geom_boxplot(aes(y=KPNIH1_RS28775_chr_median_norm, x=KPC_plasmid_simplified,alpha=0.6))  + geom_jitter(aes(y=KPNIH1_RS28775_chr_median_norm, x=KPC_plasmid_simplified),width = .25,size=2,alpha=0.6) + ylab("KPC Copy Number") + xlab("KPC Plasmid Cluster")+ theme_bw_me + sfig6_format + theme(legend.position='none') + ylim(NA,10.01)
```

# C membership in clusters
```{r} 
df_CI$AA552_like <- ifelse(df_CI$AA552_KPC==1,"Present","Absent")
df_CI$blbli_cluster_simplified <- ifelse(grepl("Cluster",df_CI$blbli_asr_cluster_renamed),"Cluster",ifelse(grepl("Singleton",df_CI$blbli_asr_cluster_renamed),"Singleton","Susceptible") )

blbli_plasmid_prop <- df_CI %>% group_by(blbli_cluster_simplified,AA552_like)  %>%
  dplyr::summarise(n = n()) %>%
  mutate(freq = n / sum(n)) %>% `colnames<-`(c("clustering_simple","AA552_like","n","freq")) %>% as.data.frame
 
C <-  ggplot(data=blbli_plasmid_prop,aes(x=clustering_simple,fill=AA552_like,y=n))+geom_bar(position="stack",stat="identity",width = .75)  +ylab("No. isolates") +xlab("Phylogenetics of resistance")   + theme_bw_me + sfig6_format  +ylim(NA,115) + AA552_fill
```

```{r ,fig.height = 10, fig.width = 10,echo=F,message=F,error=F,warning=F}
s_figure_6BC <- cowplot::plot_grid(B,C,ncol=1,labels = c("B","C"),label_size = 28) 
```

```{r ,fig.height=10,fig.width=11} 
s_figure_6A <- cowplot::plot_grid(A,labels = c("A"),label_size=28)  
```

```{r ,fig.height=12,fig.width=21.25}
s_figure_6 <- plot_grid(s_figure_6A,s_figure_6BC,rel_heights = c(1,1),rel_widths = c(1,.325))  
s_figure_6
```
 
```{r,message=F,echo=F,error=F,warning=F,fig.width=21.25,fig.height=15} 
ggsave(plot = s_figure_6, filename = './figures/s_figure_5.png', width = 21.25, height = 12,limitsize=FALSE, bg='white')
```