---
title: "Supplemental Figure 2 - Spearman’s rank correlation coefficients between the minimum inhibitory concentration of last-line and novel agents"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE) 
rm(list = ls())
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
``` 

# Environment
```{r}
#Packages
packages <- c("tidyverse","ComplexHeatmap","RColorBrewer",'circlize',"cowplot")

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
Sys.info()
sessionInfo()
``` 

# Data
```{r}
df <- readRDS("./data/dataset/df.RDS")
```

# Supplemental figure: Correlation matrix of MIC values
```{r,message=F,error=F,warning=F,fig.width=8.5,fig.height=6}
MIC_correlation <-  cor(df %>% select("MERO_log_2","MVB_log_2","IMI_log_2","IR_log_2","CZA_log_2","TGC_log_2","CST_log_2","AMK_log_2","PLZ_log_2") , method="spearman") %>% round(.,2)
 
drugs <-  rownames(MIC_correlation) %>% gsub("_log_2","",.)

corr_heatmap <- ComplexHeatmap::pheatmap(MIC_correlation %>% as.matrix,border_color = "black",name ="Spearman's rank correlation coefficient",legend=F,fontsize = 12,
    row_names_max_width = max_text_width(rownames(MIC_correlation), gp = gpar(fontsize = 14)),
    column_names_max_height = max_text_width(rownames(MIC_correlation), gp = gpar(fontsize = 14)),
    cluster_rows=T,cluster_cols = T,labels_row = drugs,labels_col=drugs,number_color = "black",breaks = c(-1,0,1),color=c("blue","white","red"),display_numbers = T)  

## Complex heatmap legend 
fig_legend <- Legend(at = c(-1, -0.5, 0, 0.5, 1),labels = c("-1.00", "-0.50", "0.00", "0.50", "1.00"),title = "Spearman's rank correlation coefficient",direction = "horizontal",col_fun = colorRamp2(breaks = c(-1,  0,  1),colors = c("blue","white","red")), title_gp = gpar(fontsize = 14),labels_gp=gpar(fontsize=12),legend_width = unit(10, "cm"), title_position = 'topcenter')
 
# Print heatmap
fig_heatmap_image <- grid.grabExpr(draw(corr_heatmap))
fig_legend_image <- grid.grabExpr(draw(fig_legend))

s_figure_2 <- plot_grid(fig_heatmap_image,fig_legend_image,ncol=1,axis="l", align="hv",rel_heights = c(1,.15))
```

# Print & Save 
```{r,message=F,error=F,warning=F,fig.width=7.25,fig.height=5}
s_figure_2
```

```{r}
ggsave(plot = s_figure_2, filename = './figures/s_figure_2.png', width = 7.25, height = 5,bg='white')
```
