---
title: "Supplemental Figure 1 - Cross-resistance profile of carbapenem-resistant Klebsiella pneumoniae ST258 isolates"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE) 
rm(list = ls())
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
``` 

# Environment
```{r}
#Packages
packages <- c("tidyverse","ComplexHeatmap","RColorBrewer",'circlize',"cowplot")

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
Sys.info()
sessionInfo()
``` 

# Data
```{r}
df <- readRDS("./data/dataset/df.RDS")
```

# Code for figure
```{r}
last_line_res_numeric <- df %>% select("MERO_dich_num","IMI_dich_num","blbli_dich_num","MVB_dich_num","IR_dich_num","CZA_dich_num","TGC_dich_num","CST_dich_num","AMK_dich_num","PLZ_dich_num") 
colnames(last_line_res_numeric) <- gsub("blbli","BL/BLI",colnames(last_line_res_numeric))

# Get content
total_occurrences <- colSums(last_line_res_numeric) 
data_matrix <- as.matrix(last_line_res_numeric)
co_occurrence <- t(data_matrix) %*% data_matrix %>% as.matrix
co_occurrence_percent <- co_occurrence / total_occurrences * 100 

co_occurrence_merged <- list()
for(i in 1:ncol(co_occurrence)){
co_occurrence_merged[[i]] <- paste0(co_occurrence[,i]," (",round(co_occurrence_percent[,i],1),"%)")
}

co_occurrence_merged <- do.call(cbind,co_occurrence_merged) %>% as.data.frame %>% `colnames<-`(gsub("_dich_num","",colnames(co_occurrence))
) %>% `rownames<-`(paste0(gsub("_dich_num","",rownames(co_occurrence))," Resistant (n = ",total_occurrences,")")) 

# Complex heatmap
drugs <- gsub("_dich_num","",colnames(co_occurrence_merged))
## Heatmap
co_occurrence_heatmap <- ComplexHeatmap::pheatmap(co_occurrence_percent %>% as.matrix,border_color = "black",name ="Cross-Resistance",legend=F,fontsize = 14,
    row_names_max_width = max_text_width(rownames(co_occurrence_merged), gp = gpar(fontsize = 20)),
    column_names_max_height = max_text_width(rownames(co_occurrence_merged), gp = gpar(fontsize = 20)),
    legend_breaks = c(0, 25, 50, 75, 100),legend_labels = c("0%", "25%", "50%", "75%", "100%"),
    cluster_rows=F,cluster_cols = F,display_numbers = as.matrix(co_occurrence_merged),labels_row = rownames(co_occurrence_merged),labels_col = drugs,number_color = "black")

## Complex heatmap legend
one_hundred_breaks <- c()
for(i in 1:100){
  one_hundred_breaks[i] <- 1*i
}  

fig_legend <- Legend(at = c(0, 25, 50, 75, 100),labels = c("0%", "25%", "50%", "75%", "100%"),title = "Cross-Resistance",direction = "horizontal",col_fun = colorRamp2(breaks = one_hundred_breaks,colors = colorRampPalette(rev(brewer.pal(n = 7, name =  "RdYlBu")))(100)), title_gp = gpar(fontsize = 20),labels_gp=gpar(fontsize=18),legend_width = unit(15, "cm"),title_position = 'topcenter')

# Print heatmap
fig_heatmap_image <- grid.grabExpr(draw(co_occurrence_heatmap))
fig_legend_image <- grid.grabExpr(draw(fig_legend))

s_figure_1 <-plot_grid(fig_heatmap_image,fig_legend_image,ncol=1,axis="l", align="hv",rel_heights = c(1,.15))  
```

# Print & Save
```{r,message=F,error=F,warning=F,fig.width=11.5,fig.height=5.5}
s_figure_1
```

```{r}
ggsave(plot = s_figure_1, filename = './figures/s_figure_1.png', width = 11.5, height = 5.5, bg = "white")
```