---
title: "generate_asr_transition_stats"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

# Environment
```{r environment, echo=T, message=T, include=T, results=T}
#Packages
packages <- c("tidyverse",'phyloAMR')   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T)) 
# Load function
source('./lib/consistent_themes.R')
# Print
Sys.info()
sessionInfo() 
``` 

# Load datasets
```{r load data,include=T,echo=T,results=F,message=F} 
# Patient Metadata
df <- readRDS("./data/dataset/df.RDS") 
blbli_asr <- readRDS("./data/asr_clustering/blbli_asr.RDS")
```
 
# Transition Analysis 
```{r}
transition_stats <- phyloAMR::asr_transition_analysis(blbli_asr$parent_child_df,node_states='joint')  %>% mutate(pheno="BL/BLI")

favorite_kable(transition_stats)

# Save
saveRDS(transition_stats,"./data/asr_clustering/blbli_transition_stats.RDS")
```
