---
title: "Generate ASR clustering using phyloAMR"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

# Environment
```{r environment, echo=T, message=T, include=T, results=T}
#Packages
packages <- c("tidyverse",'phyloAMR','ape')   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T)) 
# Load function
source('./lib/consistent_themes.R')
# Print
Sys.info()
sessionInfo() 
``` 

# Load data
```{r}
# Patient Metadata & Phylogeny
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile")   
df<- df %>% .[match(tr$tip.label,.$isolate_no),] 

# ASR models
blbli_asr <- readRDS("./data/asr_clustering/blbli_asr.RDS")
```

# Generate clustering
```{r}
# reclassify text string for figure 
reclassify_asr_resistance <- function(string){
  ifelse(string %in% c("No Feature"),"Susceptible",
         paste0("Resistant ",string))  
}
```

```{r}     
asr_clustering <- phyloAMR::asr_cluster_detection(df = df,tr = tr, tip_name_variable = "isolate_no" , patient_id="Patient_ID", parent_child_df = blbli_asr$parent_child_df, node_states = "joint", confidence = NULL, simplify_faux_clusters = TRUE, simplify_revertant = TRUE, collapse_cluster = TRUE)

asr_clustering$asr_cluster_renamed_resistant <-  reclassify_asr_resistance(asr_clustering$asr_cluster_renamed)

saveRDS(asr_clustering,'./data/asr_clustering/blbli_asr_clustering.RDS')
```
