---
title: "generate_asr_clustering"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

# Environment
```{r environment, echo=T, message=T, include=T, results=T}
#Packages
packages <- c("tidyverse",'phyloAMR','phytools','ggtree')   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))  
# Print
Sys.info()
sessionInfo() 
``` 
 
```{r load data,include=T,echo=T,results=F,message=F}
# Patient Metadata & Phylogeny
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile")   
df<- df %>% .[match(tr$tip.label,.$isolate_no),] 
# Best model call
asr_model_choices <- readRDS("./data/asr_clustering/asr_model_choices.RDS") 
asr_best_models <- asr_model_choices[["best_model"]]
```

# Run phylosuite
```{r}  
asr_model <- phyloAMR::asr(df = df,tr = tr,tip_name_var = "isolate_no",pheno='blbli_dich_num',model = asr_best_models,node_states = "joint", upper_bound=1e100, lower_bound=1e-9, conf_threshold=NULL) 
saveRDS(asr_model,"./data/asr_clustering/blbli_asr.RDS")  
```
