#!/bin/sh
cp /nfs/turbo/umms-esnitkin/Project_Penn_KPC/Sequence_data/assembly/ONT/medaka/PCMP_H148/PCMP_H148_medaka.fasta /scratch/esnitkin_root/esnitkin1/kgontjes/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance/tn4401_blast_ONT/GeneScreener/assemblies/PCMP_H148.fasta
cp /nfs/turbo/umms-esnitkin/Project_Penn_KPC/Sequence_data/assembly/ONT/medaka/PCMP_H15/PCMP_H15_medaka.fasta /scratch/esnitkin_root/esnitkin1/kgontjes/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance/tn4401_blast_ONT/GeneScreener/assemblies/PCMP_H15.fasta
cp /nfs/turbo/umms-esnitkin/Project_Penn_KPC/Sequence_data/assembly/ONT/medaka/PCMP_H173/PCMP_H173_medaka.fasta /scratch/esnitkin_root/esnitkin1/kgontjes/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance/tn4401_blast_ONT/GeneScreener/assemblies/PCMP_H173.fasta
cp /nfs/turbo/umms-esnitkin/Project_Penn_KPC/Sequence_data/assembly/ONT/medaka/PCMP_H276/PCMP_H276_medaka.fasta /scratch/esnitkin_root/esnitkin1/kgontjes/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance/tn4401_blast_ONT/GeneScreener/assemblies/PCMP_H276.fasta
cp /nfs/turbo/umms-esnitkin/Project_Penn_KPC/Sequence_data/assembly/ONT/medaka/PCMP_H307/PCMP_H307_medaka.fasta /scratch/esnitkin_root/esnitkin1/kgontjes/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance/tn4401_blast_ONT/GeneScreener/assemblies/PCMP_H307.fasta
cp /nfs/turbo/umms-esnitkin/Project_Penn_KPC/Sequence_data/assembly/ONT/medaka/PCMP_H339/PCMP_H339_medaka.fasta /scratch/esnitkin_root/esnitkin1/kgontjes/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance/tn4401_blast_ONT/GeneScreener/assemblies/PCMP_H339.fasta
cp /nfs/turbo/umms-esnitkin/Project_Penn_KPC/Sequence_data/assembly/ONT/medaka/PCMP_H416/PCMP_H416_medaka.fasta /scratch/esnitkin_root/esnitkin1/kgontjes/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance/tn4401_blast_ONT/GeneScreener/assemblies/PCMP_H416.fasta
cp /nfs/turbo/umms-esnitkin/Project_Penn_KPC/Sequence_data/assembly/ONT/medaka/PCMP_H434/PCMP_H434_medaka.fasta /scratch/esnitkin_root/esnitkin1/kgontjes/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance/tn4401_blast_ONT/GeneScreener/assemblies/PCMP_H434.fasta
