---
title: "generate_pairwise_snp_distance"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE)  
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

# Environment
```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse",'ape')   
#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
``` 

# Dataset
```{r}
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile")
```

```{r}
dna_matrix <- function(fa,reference){
  ape::dist.dna(x = fa, # DNAbin object as read in above
                as.matrix = TRUE, # return as matrix
                model = "N", # count pairwise distances
                pairwise.deletion = TRUE # delete sites with missing data in a pairwise way
  )%>%  as.data.frame %>% subset(rownames(.)!=paste0(reference)) %>% select(-all_of(reference))}
```


# Pairwise SNP Distance Matrix  
```{r}
# Recombination filtered SNPs
snps<- read.dna("~/Desktop/gl_mount/Sequence_data/variant_calling/2025-02-17_snpkit_Penn_KPC_ST258/output_files/2025_02_23_21_11_49_core_results/phylokit/results/gubbins_masked/Penn_KPC_ST258_gubbins_masked_var_sites.fa",
                format = "fasta")

# Create matrix
dna_matrix <- dna_matrix(snps,'gi|661922017|gb|CP008827.1|') %>% .[match(tr$tip.label,rownames(.)),match(tr$tip.label,rownames(.))]  
dna_matrix <- as.matrix(dna_matrix)
dim(dna_matrix)
head(dna_matrix)

saveRDS(dna_matrix,file="./data/nearest_neighbor_comparisons/pairwise_snp_dist_mat.RDS")
write_csv(as.data.frame(dna_matrix),file="./data/nearest_neighbor_comparisons/pairwise_snp_dist_mat.csv")
```