---
title: "Supplemental Table 2: Log2 kpc regression modeling"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","gridExtra",'kableExtra',"tableone","ape","ggtree",'sjPlot','webshot2')

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Scripts
source("./lib/consistent_themes.R") 
source("./lib/common_functions.R")
```

```{r} 
# Standard data
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile") 
## Canonical
canonical <- readRDS("./data/carbapenem_resistance_panel/carbapenem_resistance_panel_matrix.RDS")
## Depth
depth <- readRDS("./data/KPC_coverage/normalized/KPNIH1_KPC_plasmid_depth_by_feature_median_chromosome_normalized.RDS")
# Join 
df <- left_join(df,canonical %>% mutate(isolate_no = rownames(.))) 
df <- left_join(df,depth %>% mutate(isolate_no = rownames(.)))
```

# Log-2 KPC association with MICs
 
```{r} 
convert_tableone_into_df(df,c("OmpK36_L3_mutations","OmpK36GD","OmpK36TD"),strata="clade_I",outcome_names = c("Clade I","Clade II"),factorVars = c("OmpK36_L3_mutations","OmpK36GD","OmpK36TD"))
 
# Simple ompK36 status
df$OmpK36_mutations_simple <- ifelse(df$OmpK36_putative_function_altering==1 | df$OmpK36_truncation_kleborate==1 ,"Putative function-altering variant (PFAV)",
                                     ifelse(df$OmpK36_L3_mutations==1, "Loop 3 insertion","No loop 3 insertion or PFAV"))

df$OmpK36_mutations_simple <- factor(df$OmpK36_mutations_simple, levels=rev(c("No loop 3 insertion or PFAV","Loop 3 insertion","Putative function-altering variant (PFAV)")))
# Easy variable
df$KPC_log_2 <- log2(df$KPNIH1_RS28775_chr_median_norm)
```

```{r}
df_w_KPC <- df %>% subset(KPNIH1_RS28775_chr_median_norm >0)
df_w_KPC$OmpK36_mutations_simple <- relevel(df_w_KPC$OmpK36_mutations_simple,ref = "No loop 3 insertion or PFAV") 

paste0("KPC w/ MVB")
MVB_simple <- lm(MVB_log_2 ~ KPC_log_2 ,data=df_w_KPC)   
MVB_adjusted <- lm(MVB_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC) 
MVB_interaction <-  lm(MVB_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC) 
MVB_summary <- tab_model(MVB_simple,MVB_adjusted,MVB_interaction,show.se = T,show.aic = T)

paste0("IR w/ KPC")
IR_simple <- lm(IR_log_2 ~ KPC_log_2 ,data=df_w_KPC)  
IR_adjusted <- lm(IR_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC)  
IR_interaction <- lm(IR_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC)   
IR_summary <- tab_model(IR_simple,IR_adjusted,IR_interaction,show.se = T,show.aic = T)

regression_results <- list(MVB_simple=MVB_simple,MVB_adjusted=MVB_adjusted,MVB_interaction=MVB_interaction,IR_simple=IR_simple,IR_adjusted=IR_adjusted,IR_interaction=IR_interaction)

saveRDS(object = regression_results,file = "./tables/s_table_2.RDS")

table_reg <- tab_model(MVB_simple,MVB_adjusted,MVB_interaction,IR_simple,IR_adjusted,IR_interaction,show.se = T,show.aic = T,file = NULL)  
table_reg

html_file <- "tables/s_table_2.html"
writeLines(as.character(table_reg$page.complete), html_file)
```