---
title: "Supplemental Table 1: Clade-specific trends in the prevalence of carbapenem resistance-associated genotypes"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
--- 
# Combination Therapy Manuscript
```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","ggnewscale","tableone","kableExtra")

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Scripts
source("./lib/consistent_themes.R")
source("./lib/common_functions.R")
```

# Data
```{r}
df <- readRDS("./data/dataset/df.RDS") 
# Canonical
canonical <- readRDS("./data/carbapenem_resistance_panel/carbapenem_resistance_panel_matrix.RDS")
df <- left_join(df,canonical)

# tn4401 data
tn4401 <- readRDS("./data/TETyper/TETyper_curated.RDS")  
df <- left_join(df,tn4401)

# load the kleborate
kleborate <- readRDS("./data/kleborate/kleborate_curated.RDS") %>% as.data.frame
df <- left_join(df,kleborate)

# Load blast data 
KPC_data <- read.table("./data/KPC_blast/KPC_blast_master.txt",header = T)  
KPC_data$KPC_allele <- ifelse(grepl("KPC-3",KPC_data$sseqid) ==T,"KPC-3",
                                ifelse(grepl("KPC-5",KPC_data$sseqid) ==T,"KPC-5",
                                ifelse(grepl("KPC-2",KPC_data$sseqid) ==T,"KPC-2",
                                ifelse(grepl("KPC-10",KPC_data$sseqid) ==T,"KPC-10","No KPC"))))
df <- left_join(df,KPC_data %>% select(isolate_no,KPC_allele))
df$KPC_allele <- ifelse(is.na(df$KPC_allele),"No KPC",df$KPC_allele)
df$`KPC-10` <- ifelse(df$KPC_allele=="KPC-10",1,0)
```

# Blactamase gene curation
```{r}
# B-lactamase genes  
bla_variables <- c("Bla_acquired","Bla_ESBL_acquired","Bla_Carb_acquired","Bla_chr")
rownames(kleborate) <- kleborate$isolate_no

bla_mat<- lapply(bla_variables,FUN=function(x){get_presence_absence_matrix(x,kleborate)}) %>% do.call(cbind,.) %>% as.data.frame %>% mutate(isolate_no = rownames(.)) 

## Edit similar b-lactamase gene calls
bla_mat$`KPC-3` <- ifelse(bla_mat$`KPC-3`==1 | bla_mat$`KPC-3^`,1,0)
bla_mat$`SHV-11` <- ifelse(bla_mat$`SHV-11`==1 | bla_mat$`SHV-11^`,1,0)
bla_mat$`SHV-12` <- ifelse(bla_mat$`SHV-12`==1 ,1,0)
bla_mat$`TEM-1D.v1` <- ifelse(bla_mat$`TEM-1D.v1^` ==1 | bla_mat$`TEM-1D.v1`==1,1,0)

bla_genes <- c(colnames(bla_mat %>% select(-isolate_no)),"KPC-10") %>% sort %>% subset(!.%in% c("KPC-3^","SHV-11^","SHV-12^","TEM-1D.v1^"))
df <- left_join(df,bla_mat)
```

# Variable curation
```{r}
drug_entry <- c('OmpK35-25%','OmpK36_c25t','OmpK36_L3_mutations','OmpK36GD','OmpK36TD','OmpK36_non_syn','OmpK36_putative_function_altering',"OmpK36_truncation_kleborate",'OmpK36_intergenic','OmpK36_promoter_IS')
drug_exit <- c("AcrAB_TolC_any",'RamR',"RamA")
target_modification <- c('PBP_any','PBP2',"PBP4")

carbapenem <- c(drug_entry,drug_exit,target_modification)

tn4401 <- c("Tn4401a","Tn4401b","Tn4401d","Tn4401_del_6920_7126","Tn4401_del_1_554_7008_7075","Tn4401_del_1_3391_6920_7126")
```

# Table curation

```{r} 
exact <- c("OmpK36TD",'OmpK36_truncation_kleborate',"OmpK36_putative_function_altering","OmpK36_intergenic","OmpK36_promoter_IS","AcrAB_TolC_any","RamR","RamA","PBP_any","PBP2","PBP4",'Tn4401_del_1_3391_6920_7126','CMY-2.v2','CTX-M-14','CTX-M-15',"KPC-5","LAP-2","OXA-1","TEM-1",'TEM-104?','TEM-104*?','TEM-150*?')

s_table_1 <- convert_tableone_into_df(dataset = df,vars=c(carbapenem,bla_genes,tn4401),factorVars = c(carbapenem,bla_genes,tn4401),strata="clade_I",outcome_names = c("Clade I","Clade II"),exact=exact)
s_table_1$Variable <- gsub(" \\= 1","",s_table_1$Variable) %>% gsub(" \\(|\\)|\\%","",.) 

s_table_1$Variable <- recode_genotypes(s_table_1$Variable)

s_table_1 <-  s_table_1 %>% as.data.frame

# Recode blactamase genes
s_table_1$Variable <- ifelse(s_table_1$Variable %in% bla_genes,
                             paste0("bla",s_table_1$Variable),s_table_1$Variable)

# Recode tn4401s
s_table_1$Variable <- recode(s_table_1$Variable, 
                             "Tn4401_del_6920_7126" = "Tn4401 del 6920-7126",
                             "Tn4401_del_1_554_7008_7075" = "Tn4401 del 1-554 7008-7075",
                             "Tn4401_del_1_3391_6920_7126" = "Tn4401 del 1-3391 6920-7126") %>% gsub("Tn4401","tn4401",.)


favorite_kable(s_table_1)
```

# Save the table
```{r}
write_csv(s_table_1,"./tables/s_table_1.csv")
saveRDS(s_table_1,"./tables/s_table_1.RDS")
```