---
title: "Supplemental Tables 3-5: Descriptive stats + regression modeling for BL/BLI resistance mechanism"
output: html_document
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

# Environment

```{r}
library(tidyverse)
library(data.table)
library(tableone)
library(kableExtra)
source("./lib/consistent_themes.R")
```

# Load data

```{r}
descriptive_stats <- readRDS("./data/regression/descriptive_stats.RDS") 
purposeful_results <- readRDS("./data/regression/purposeful_regression_results.RDS")
```

# Raw data 

```{r}
purposeful_results$univariable$present
purposeful_results$univariable$singleton
purposeful_results$univariable$cluster

purposeful_results$multivariable$present$final_model_table
purposeful_results$multivariable$singleton$final_model_table
purposeful_results$multivariable$cluster$final_model_table
```

# Curate tables

```{r}
table_curation <- function(stats,ulogr,mlogr){
  stats <- stats[,c(6,2,4,3)] 
  # Format the tables
  ## ulogr
  ulogr$OR <- formatC(ulogr$OR, format = "f", digits = 2)
  ulogr$`2.5%` <- formatC(ulogr$`2.5%`, format = "f", digits = 2)
  ulogr$`97.5%` <-   formatC(ulogr$`97.5%`, format = "f", digits = 2)
  ulogr$`OR (95% CI)` <- paste0(ulogr$OR," (",ulogr$`2.5%`,"-",ulogr$`97.5%`,")")
  ## Mlogr
  mlogr$OR <- formatC(mlogr$OR, format = "f", digits = 2)
  mlogr$`2.5%` <- formatC(mlogr$`2.5%`, format = "f", digits = 2)
  mlogr$`97.5%` <-   formatC(mlogr$`97.5%`, format = "f", digits = 2)
  mlogr$`OR (95% CI)` <- paste0(mlogr$OR," (",mlogr$`2.5%`,"-",mlogr$`97.5%`,")")
  
  ulogr <- ulogr %>% select(variable, `OR (95% CI)`, p_value) %>% `colnames<-`(c("term","OR (95% CI)","OR p-value"))
  ulogr$term <- as.character(ulogr$term)
  mlogr <- mlogr %>% select(variable, `OR (95% CI)`, p_value) %>% `colnames<-`(c("term","aOR (95% CI)","aOR p-value"))
  mlogr$term <- as.character(mlogr$term)
  results <- left_join(stats,ulogr) %>% left_join(mlogr) 
  # Column names
  colnames(results) <- recode(colnames(results),
                       "term" = "Variable")
  # Variable rename
  results$Variable <- recode(results$Variable,
                              "age" = "Age, 1 year unit",
                              "LOSbeforeCx" = "Length of stay before culture, 1-day unit" ,
                              "sex.female" = "Female sex",
                              "trach" = "Tracheostomy tube",
                              "central_line" = "Central venous catheter",
                              "foley" = "Indwelling urinary catheter",
                              "gastro" = "Gastrostomy tube",
                              "AKI" = "Acute kidney injury",
                              "CKD" = "Chronic kidney disease",
                              "VDRF" = "Ventilator-dependent respiratory failure",
                              "underweight" = "Underweight or malnutrition",
                              "CHF" = "Congestive heart failure",
                              "decub" = "Decubitus ulcer stage 4+",
                              "lung_dz" = "Chronic bronchitis or chronic obstructive pulmonary disease",
                              "brain_injury" = "Brain injury",
                              "malignancy" = "Malignancy",
                              "obese" = "Obesity",
                              "carbapenem_1d" = "Carbapenem exposure",
                              "amikacin_1d" = "Amikacin exposure",
                              "gent_1d" = "Gentamicin exposure",
                              "tobra_1d" = "Tobramycin exposure",
                              "aztreonam_1d" = "Aztreonam exposure",
                              "bactrim_1d" = "Sulfamethoxazole-trimethoprim exposure",
                              "third_plus_ceph_1d" = "Cephalosporin exposure",
                              "FQ_1d" = "Fluoroquinolone exposure",
                              "dapto_1d" = "Daptomycin exposure",
                              "flagyl_1d" = "Metronidazole exposure",
                              "linezolid_1d" = "Linezolid exposure",
                              "poly_colistin_1d" = "Polymyxin and/or colistin exposure",
                              "tigecycline_1d" = "Tigecycline exposure",
                              "vanco_1d" = "Vancomycin exposure",
                              "zosyn_1d"  = "Piperacillin/tazobactam exposure") 
  # Recode NAs
  results$`OR (95% CI)` <- gsub(" NA","NA",results$`OR (95% CI)`)
  results$`aOR (95% CI)` <- gsub(" NA","NA",results$`aOR (95% CI)`)
  return(results)
}
```

```{r}
s_table_3 <- table_curation(descriptive_stats$present,purposeful_results$univariable$present,purposeful_results$multivariable$present$final_model_table)
s_table_4 <- table_curation(descriptive_stats$singleton,purposeful_results$univariable$singleton,purposeful_results$multivariable$singleton$final_model_table)
s_table_5 <- table_curation(descriptive_stats$cluster,purposeful_results$univariable$cluster,purposeful_results$multivariable$cluster$final_model_table)
```

# Update table names
```{r}
paste0("Raw column: ")
colnames

```


# Print tables

```{r}
s_table_3 %>% favorite_kable()
s_table_4 %>% favorite_kable()
s_table_5 %>% favorite_kable()
```

# Save tables

```{r}
write_csv(s_table_3,"./tables/s_table_3.csv")
saveRDS(s_table_3,"./tables/s_table_3.RDS")

write_csv(s_table_4,"./tables/s_table_4.csv")
saveRDS(s_table_4,"./tables/s_table_4.RDS")

write_csv(s_table_5,"./tables/s_table_5.csv")
saveRDS(s_table_5,"./tables/s_table_5.RDS")
```
