---
title: "Convergence-based genome-wide association study identified additional resistance-associated genotypes"
output: html_document
date: "`r Sys.Date()`"
---
```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
```

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","gridExtra",'kableExtra',"tableone","ape","ggtree")

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

#Scripts
source("./lib/consistent_themes.R")
source("./scripts/GWAS/analysis/GWAS_analysis_scripts.R")
source("./lib/common_functions.R")
```

```{r} 
# Standard data
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile")
# GWAS table
gwas_table <- readRDS("./data/GWAS/hits/gwas_hits_table.RDS")
gwas_mat <- readRDS("./data/GWAS/hits/gwas_mat.RDS")
# Genome features
KPNIH1_features <- readRDS("./data/references/KPNIH1/KPNIH1_features.RDS")
# Matrices
## Kleborate matrix
kleborate <- readRDS("./data/GWAS/matrices/kleborate_mat.RDS") %>% as.data.frame 
## KPC Plasmids 
KPC_info_clusters <- readRDS("./data/KPC_plasmid/KPC_containing_clusters_mat.RDS") %>% as.data.frame 
KPC_containing_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_KPC")) %>% {ifelse(.=="KPC Plasmid",1,0)} %>% as.data.frame%>% select_if(colSums(.)>0)
KPC_clusters <- colnames(KPC_containing_clusters)
Non_KPC_clusters <- KPC_info_clusters %>% `colnames<-`(paste0(colnames(.),"_non_KPC")) %>% {ifelse(.=="Non-KPC plasmid",1,0)} %>% as.data.frame %>% select_if(colSums(.)>0)
df <- left_join(df,KPC_containing_clusters %>% mutate(isolate_no = rownames(.))) %>% left_join(Non_KPC_clusters %>% mutate(isolate_no = rownames(.)))
## Core genome burden models
models <- c("model1","model1.2","model2","model2.2","model3","model3.2")
for(x in models){
  grouped_model <- paste0(x,"_burden.RDS")
  assign(gsub(".RDS","",grouped_model),readRDS(paste0("./data/GWAS/matrices/",grouped_model)) %>% as.data.frame)
}
## BLBLI clustering
pclustering <- readRDS('./data/asr_clustering/blbli_asr_clustering_df.RDS')
blbli_asr <- readRDS('./data/asr_clustering/blbli_asr.RDS')
## Canonical
canonical <- readRDS("./data/carbapenem_resistance_panel/carbapenem_resistance_panel_matrix.RDS")
## Depth
depth <- readRDS("./data/KPC_coverage/normalized/KPNIH1_KPC_plasmid_depth_by_feature_median_chromosome_normalized.RDS")
# Join
df <- left_join(df,kleborate %>% mutate(isolate_no = rownames(.)))
df <- left_join(df,gwas_mat %>% mutate(isolate_no = rownames(.))) 
df <- left_join(df,pclustering %>% select(isolate_no,blbli_asr_cluster_renamed))
df$blbli_asr_cluster_renamed_simple <- recode(df$blbli_asr_cluster_renamed,"No Feature"="Susceptible" )
   
df <- left_join_matrix(model1_burden,df,"_1")
df <- left_join_matrix(model1.2_burden,df,"_1.2")
df <- left_join_matrix(model2_burden,df,"_2")
df <- left_join_matrix(model2.2_burden,df,"_2.2")
df <- left_join_matrix(model3_burden,df,"_3")
df <- left_join_matrix(model3.2_burden,df,"_3.2")
df <- left_join(df,canonical %>% mutate(isolate_no = rownames(.))) 
df <- left_join(df,depth %>% mutate(isolate_no = rownames(.)))
```

# Overview
```{r}
paste0("Number of gwas hits: ", nrow(gwas_table))

paste0("Resistance category:")
table(gwas_table$resistance_category)

paste0("How many passed QC:")
table(gwas_table$nn_qc)
```

# Four modulators
```{r}
continuous <- gwas_table %>% subset(resistance_category == "Modulator")

paste0("Number of continuous hits: ")
nrow(continuous)

paste0("Number of continuous hits passing qc: ")
continuous_pass <- subset(continuous, nn_qc=="Yes")
nrow(continuous_pass)

paste0("Genotypes passing:") 
library(rstatix)
enrichment <- function(group,df){
  group_df <- df %>% subset(get(group)==1)
  wo_df <- df %>% subset(get(group)==0)
  # MVB
  ## Median IQR
  MVB_median_with <-  median(group_df[,'MVB_log_2'])
  MVB_IQR_with <-  IQR(group_df[,'MVB_log_2'])
  MVB_median_IQR_with <-  paste0(MVB_median_with," (",MVB_IQR_with,")")  
  MVB_median_wo <-  median(wo_df[,'MVB_log_2'])
  MVB_IQR_wo <-  IQR(wo_df[,'MVB_log_2'])
  MVB_median_IQR_wo <-  paste0(MVB_median_wo," (",MVB_IQR_wo,")") 
  ## T test
  MVB_t_test <- wilcox.test(df[,group], df[,"MVB_log_2"], conf.int=TRUE)    
  MVB_t_test_p <- MVB_t_test$p.value
  MVB_t_test_estimate <- wilcox_effsize(data = df,formula = as.formula(paste0("MVB_log_2","~",group)),paired = F) %>% .$effsize
  
  # IR
  ## Median IQR
  IR_median_with <-  median(group_df[,'IR_log_2'])
  IR_IQR_with <-  IQR(group_df[,'IR_log_2'])
  IR_median_IQR_with <-  paste0(IR_median_with," (",IR_IQR_with,")")  
  IR_median_wo <-  median(wo_df[,'IR_log_2'])
  IR_IQR_wo <-  IQR(wo_df[,'IR_log_2'])
  IR_median_IQR_wo <-  paste0(IR_median_wo," (",IR_IQR_wo,")")  
  ## T test
  IR_t_test <- wilcox.test(df[,group], df[,"IR_log_2"], conf.int=TRUE) 
  IR_t_test_p <- IR_t_test$p.value
  IR_t_test_estimate <- wilcox_effsize(data = df,formula = as.formula(paste0("IR_log_2","~",group)),paired = F) %>% .$effsize
  return(data.frame(genotype=group,MVB_median_IQR_with,MVB_median_IQR_wo,MVB_t_test_estimate,MVB_t_test_p,IR_median_IQR_with,IR_median_IQR_wo,IR_t_test_estimate,IR_t_test_p))
}

lapply(continuous_pass$genotype,FUN=enrichment,df) %>% do.call(rbind,.) %>% favorite_kable
  

continuous_pass %>% select(locus_tag,product,MVB_num_log_2_diff_increase_prop,MVB_num_log_2_diff_decrease_prop,MVB_num_log_2_diff_median,MVB_num_log_2_diff_range,IR_num_log_2_diff_increase_prop,IR_num_log_2_diff_decrease_prop,IR_num_log_2_diff_median,IR_num_log_2_diff_range,genotype,sig_tests,sig_phenotypes)  %>% favorite_kable
```

# AA552 plasmid
```{r}
gwas_table %>% subset(genotype %in% c("AA018","AA552")) %>% select(locus_tag,product,blbli_dich_num_binary_diff_gain_prop,blbli_dich_num_binary_diff_loss_prop,MVB_num_log_2_diff_increase_prop,MVB_num_log_2_diff_decrease_prop,MVB_num_log_2_diff_median,MVB_num_log_2_diff_range,IR_num_log_2_diff_increase_prop,IR_num_log_2_diff_decrease_prop,IR_num_log_2_diff_median,IR_num_log_2_diff_range,genotype,sig_tests,sig_phenotypes) %>% favorite_kable 

plasmid_table <- table(df$AA552_KPC,df$blbli_dich_num) 
plasmid_table
prop.table(plasmid_table,margin=2)
chisq.test( plasmid_table) 
```

# Log-2 KPC association

## OmpK36 GD insertion story
```{r} 
convert_tableone_into_df(df,c("OmpK36_L3_mutations","OmpK36GD","OmpK36TD"),strata="clade_I",outcome_names = c("Clade I","Clade II"),factorVars = c("OmpK36_L3_mutations","OmpK36GD","OmpK36TD"))
 
# Simple ompK36 status
df$OmpK36_mutations_simple <- ifelse(df$OmpK36_putative_function_altering==1 | df$OmpK36_truncation_kleborate==1 ,"Putative function-altering variant (PFAV)",
                                     ifelse(df$OmpK36_L3_mutations==1, "Loop 3 insertion","No loop 3 insertion or PFAV"))

df$OmpK36_mutations_simple <- factor(df$OmpK36_mutations_simple, levels=rev(c("No loop 3 insertion or PFAV","Loop 3 insertion","Putative function-altering variant (PFAV)")))
# Easy variable
df$KPC_log_2 <- log2(df$KPNIH1_RS28775_chr_median_norm)
```

```{r}
df_w_KPC <- df %>% subset(KPNIH1_RS28775_chr_median_norm >0)
df_w_KPC$OmpK36_mutations_simple <- relevel(df_w_KPC$OmpK36_mutations_simple,ref = "No loop 3 insertion or PFAV") 
paste0("KPC w/ MVB or IR")
lm(MVB_log_2 ~ KPC_log_2 ,data=df_w_KPC) %>% summary 
lm(MVB_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC) %>% summary  
lm(MVB_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC) %>% summary 


paste0("IR w/ KPC")
lm(IR_log_2 ~ KPC_log_2 ,data=df_w_KPC) %>% summary 
lm(IR_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC) %>% summary  
lm(IR_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC) %>% summary  
```
### Investigation across clades
```{r}
df_w_KPC_CI <- df_w_KPC %>% subset(clade_I == "Clade I")
df_w_KPC_CII <- df_w_KPC %>% subset(clade_I != "Clade I")
# Clade I
paste0("KPC w/ MVB or IR")
lm(MVB_log_2 ~ KPC_log_2 ,data=df_w_KPC_CI) %>% summary 
lm(MVB_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC_CI) %>% summary  
lm(MVB_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC_CI) %>% summary 


paste0("IR w/ KPC")
lm(IR_log_2 ~ KPC_log_2 ,data=df_w_KPC_CI) %>% summary 
lm(IR_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC_CI) %>% summary  
lm(IR_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC_CI) %>% summary  
```






```{r}
df_CI <- df %>% subset(clade_I == "Clade I")
convert_tableone_into_df(df_CI,vars = c("OmpK36_L3_mutations","OmpK36GD","OmpK36TD"),factorVars = c("OmpK36_L3_mutations","OmpK36GD","OmpK36TD"))
 
df_w_KPC_CI <- df_w_KPC %>% subset(clade_I == "Clade I")
df_w_KPC_CII <- df_w_KPC %>% subset(clade_I != "Clade I")
 
paste0("MVB w/ KPC")
lm(MVB_log_2 ~ KPC_log_2 ,data=df_w_KPC) %>% summary 
lm(MVB_log_2 ~ KPC_log_2 ,data=df_w_KPC_CI) %>% summary 
lm(MVB_log_2 ~ KPC_log_2 ,data=df_w_KPC_CII) %>% summary 
paste0("MVB w/ KPC controlling for ompk36 status")
lm(MVB_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC) %>% summary 
lm(MVB_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC_CI) %>% summary 
lm(MVB_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC_CII) %>% summary 
paste0("MVB w/ KPC modeling ompk36 status as an interaction term")
lm(MVB_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC) %>% summary 
lm(MVB_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC_CI) %>% summary 
lm(MVB_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC_CII) %>% summary 

paste0("IR w/ KPC")
lm(IR_log_2 ~ KPC_log_2 ,data=df_w_KPC) %>% summary
lm(IR_log_2 ~ KPC_log_2 ,data=df_w_KPC_CI) %>% summary
lm(IR_log_2 ~ KPC_log_2 ,data=df_w_KPC_CII) %>% summary
paste0("IR w/ KPC controlling for ompk36 status")
lm(IR_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC) %>% summary
lm(IR_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC_CI) %>% summary
lm(IR_log_2 ~ KPC_log_2 + OmpK36_mutations_simple,data=df_w_KPC_CII) %>% summary
paste0("IR w/ KPC modeling ompk36 status as an interaction term")
lm(IR_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC) %>% summary
lm(IR_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC_CI) %>% summary
lm(IR_log_2 ~ KPC_log_2 * OmpK36_mutations_simple,data=df_w_KPC_CII) %>% summary
```

# FJ223607 Story
## Validation of hits
```{r}
gwas_table %>% subset(genotype %in% c("AA018","AA552")) %>% select(locus_tag,product,MVB_num_log_2_diff_increase_prop,MVB_num_log_2_diff_decrease_prop,MVB_num_log_2_diff_median,MVB_num_log_2_diff_range,IR_num_log_2_diff_increase_prop,IR_num_log_2_diff_decrease_prop,IR_num_log_2_diff_median,IR_num_log_2_diff_range,genotype,sig_tests,sig_phenotypes) %>% favorite_kable 
```

```{r}
convert_tableone_into_df(df_CI,vars=c("AA018","AA552"),factorVars = c("AA018","AA552"))
enrichment("AA552",df_CI) 

wilcox.test(df_CI[,"AA552"],df_CI[,"KPC_log_2"],alternative='two.sided')

enrichment("AA552",df_CI)
```

```{r}
table(df_CI$AA018_KPC,df_CI$AA552_non_KPC)
convert_tableone_into_df(df_CI,"AA552_non_KPC",strata="AA018_KPC",factorVars = "AA552_non_KPC",outcome_names = c("Absent","Present"))
convert_tableone_into_df(df_CI,"AA018_non_KPC",strata="AA552_KPC",factorVars = "AA018_non_KPC",outcome_names = c("Absent","Present"))
```
# Synchronous
```{r}
synchronous <- gwas_table %>% subset(resistance_category != "Modulator")

paste0("Number of synchronous hits")
nrow(synchronous)

paste0("Synchronous hits that passed QC")
synchronous_pass <- subset(synchronous, nn_qc=="Yes")

synchronous_pass %>% select(locus_tag,gene,product,blbli_res_freq,blbli_sus_freq,`Singleton_prop`,blbli_dich_num_binary_diff_gain_prop,blbli_dich_num_binary_diff_loss_prop,best_model,genotype)  %>% favorite_kable

novel_synchronous <- synchronous_pass %>% subset(!locus_tag %in% c("KPNIH1_RS18665","KPNIH1_RS07805")) %>% .$genotype
```
### AA552
```{r}
paste0("Nearest neigbor data")
AA552_data <- synchronous_pass %>% subset(locus_tag == "AA552")
AA552_data %>% select(blbli_sus_freq,blbli_sus_prop,blbli_res_freq,blbli_res_prop,blbli_dich_num_binary_diff_gain_prop,blbli_dich_num_binary_diff_loss_prop,MVB_num_diff_increase_prop,MVB_num_log_2_diff_median,MVB_num_log_2_diff_range,IR_num_diff_increase_prop,IR_num_log_2_diff_median,IR_num_log_2_diff_range)

paste0("Frequency and enr")
convert_tableone_into_df(df,vars = "AA552",strata='blbli_dich',outcome_names = c("Susceptible","Resistant"),factorVars='AA552')
```

```{r}
paste0("Nearest neigbor data")
AA018_data <- synchronous_pass %>% subset(locus_tag == "AA018")
AA018_data %>% select(blbli_sus_freq,blbli_sus_prop,blbli_res_freq,blbli_res_prop,blbli_dich_num_binary_diff_gain_prop,blbli_dich_num_binary_diff_loss_prop,MVB_num_diff_increase_prop,MVB_num_log_2_diff_median,MVB_num_log_2_diff_range,IR_num_diff_increase_prop,IR_num_log_2_diff_median,IR_num_log_2_diff_range)

paste0("Frequency and enr")
convert_tableone_into_df(df,vars = "AA018",strata='blbli_dich',outcome_names = c("Susceptible","Resistant"),factorVars='AA018')
```
## AA018 vs. AA552
```{r}
df_CI <- df %>% subset(clade_I=="Clade I")

convert_tableone_into_df(df_CI,vars = c("AA552","AA018"),strata='blbli_dich_num',outcome_names = c("Susceptible","Resistant"),factorVars=c("AA552","AA018"))

enrichment("AA552",df_CI) 

wilcox.test(df_CI[,"AA552"],df_CI[,"KPC_log_2"],alternative='two.sided')

paste0("Plasmid differences: ")

convert_tableone_into_df(df_CI,vars = c("AA552_non_KPC"),strata='AA018_KPC',outcome_names = c("Absent","Present"),factorVars=c("AA552_non_KPC"))

convert_tableone_into_df(df_CI,vars = c("AA018_non_KPC"),strata='AA552_KPC',outcome_names = c("Absent","Present"),factorVars=c("AA018_non_KPC"))
```
