---
title: "Known carbapenem resistance-associated genotypes moderately explain resistance in a clade-specific manner"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE) 
rm(list = ls())
opts_knit$set(root.dir='~/Desktop/gl_mount/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/')
``` 

```{r}
library(tidyverse)
library(tableone)
library(ggtree)
library(tableone)
library(kableExtra)

source("./lib/common_functions.R")
source("./lib/consistent_themes.R")  

# Print environment
Sys.info()
sessionInfo()
```

# Data
```{r}
df <- readRDS("./data/dataset/df.RDS")
tr <- read.tree("./data/tree/tree.treefile")
df <- df %>% .[match(tr$tip.label,.$isolate_no),]  
canonical <- readRDS("./data/carbapenem_resistance_panel/carbapenem_resistance_panel_matrix.RDS")
df <- left_join(df,canonical)
kleborate <- readRDS("./data/kleborate/kleborate_curated.RDS")
df <- left_join(df,kleborate %>% select(isolate_no,KPC_type))

nn <- readRDS("./data/nearest_neighbor_comparisons/nn_comparisons.RDS")
```


# KPC frequency
```{r}
table(df$KPC_type)
convert_tableone_into_df(df,vars="KPC_type")
```

# Get NN passing data list
```{r}
get_summary_statistics <- function(name,nn_list){
  obj <- nn_list[[name]]
  obj[["nn_comps_with_variant_sum"]]
}

get_nn_flag <- function(gwas_table){
  gwas_table$nn_qc <- ifelse(c(abs(gwas_table$MVB_num_log_2_diff_median) >1 | abs(gwas_table$IR_num_log_2_diff_median) >1),"yes","no")  
  return(gwas_table)  
}
```

```{r}
canonical_var <- canonical %>% select(-isolate_no,-`OmpK35-25%`) %>% colnames()
nn_data <- lapply(canonical_var,get_summary_statistics,nn) %>% do.call(rbind,.) %>% mutate(variable = canonical_var)  
nn_data <- get_nn_flag(nn_data)
pass_nn_qc <- subset(nn_data,nn_qc=="yes")
pass_nn_qc$variable %>% sort
```

```{r}
convert_tableone_into_df(df,vars=c('OmpK36_c25t',"OmpK36_L3_mutations"),strata='clade_I',factorVars = c('OmpK36_c25t',"OmpK36_L3_mutations"),outcome_names = c("Clade I","Clade II")) %>% gontjesr::favorite_kable()
```


# See frequency data in table 1 
# Frequency across clades found in supplemental table 1
# Panel behavior found in overall supplemental panel figure
